### ISSUE TITLE
m2 Maven console output text color unreadable in dark theme

### ISSUE THREAD

**Issue by astrapotro** [eclipse-m2e/m2e-core#1003]
Color of m2 Maven Console output text using dark theme in eclipse is absolutely unreadable:
![imagen](https://user-images.githubusercontent.com/9614789/197746007-972178b8-a5c5-4854-ae95-16896f1821f3.png)
I've tested all to change it but no success

----------------------------------
Eclipse.org - m2e	Maven Integration for Eclipse	1.9.0.20180606-2036

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2022-09 (4.25.0)
Build id: 20220908-1902

----------------------------------

Original issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=350953

**Comment by akurtakov** [comment]
@mihnita Is there a chance you can help with this one?

**Comment by astrapotro** [comment]
> The M2E version looks quite old. Can you please try the latest version from https://download.eclipse.org/technology/m2e/releases/

Thanks !! Updated m2 to 2.0.5 did the trick :
![imagen](https://user-images.githubusercontent.com/9614789/197789280-5955e628-e736-422f-8f2a-099471e1870c.png)

Anyway , is any way to change maven console colors easily ?

thanks for your work

**Comment by mihnita** [comment]
That last screen is also a bit weird, as it has no color at all.
The normal maven output uses color for the log level, and a bit of styling on the jar and artifact names, "BUILD SUCCESS" and a few other places.
The timestamp in front of the level is also unusual.
This whole think looks like the output of a logger in the code itself, not maven.

**Comment by astrapotro** [comment]
The timestamp seems to be ok, is our timezone in Spain. 

> This whole think looks like the output of a logger in the code itself, not maven.

I only do a maven update project from eclipse's right button dialog when clicking in a project. I think thats executes m2 to do that update, so, sorry for my unkownledge, but can't understand what's going on.

**Comment by mihnita** [comment]
> The timestamp seems to be ok, is our timezone in Spain.

Sure, I got that.
What is weird is the presence of that timestamp.

When maven runs, you will normally get outputs from various areas:
* maven proper
* some maven plugins
* the code being executed / tested might log stuff

The first and second kind tend to use the same logging library, with the same configuration.
And it looks something like this:
https://mihai-nita.net/wp-content/uploads/2020/08/DarkColorsFromRun.png

Note how there is no timestamp, and only the log level (and a couple of other elements) are colored.
The third one is the code of the component itself logging.
And it often is a different logger than maven, and with different configuration.
That's what we see in the screenshot.

So the colors come from the configuration of that logger.
Which is under the user control (you), not maven or Eclipse or the ANSI extension.
And if that config says "blue", then blue it is. It is very likely blue when it runs outside of eclipse.
The only thing one can do to make it more readable is to choose a different color palette from the ANSI support preferences page.

Anyway...
All good as long as you have the problem fixed.

**Comment by HannesWell** [comment]
> > The timestamp seems to be ok, is our timezone in Spain.
> 
> Sure, I got that. What is weird is the presence of that timestamp.
> 

It looks in the picture it is M2E's `Maven Console` that you can open in the Console View and that shows the log-print out of the Maven plugins that are executed within the IDE during workspace build:
![grafik](https://user-images.githubusercontent.com/44067969/198382459-c07a0a92-221a-4d21-b68e-cd3ec1f3affe.png)

@mihnita I think what you are referring is the Console printout of a Maven build process, which is displayed in the Console View as well, but as output of a launched Java-process.

**Comment by HannesWell** [comment]
However, the `Maven Console` is configured by logback configuration in the `org.eclipse.m2e.logback` plugin.
Upon first initialization that plugin copies the config `<workspace-root>/.metadata/.plugins/org.eclipse.m2e.logback` (with a version prefix) and reads it from there.
So if you want to modify the logger printout you can modify it there.

**Comment by mihnita** [comment]
First round of digging...

Logback uses blue for info level by default:
See the table at https://logback.qos.ch/manual/layouts.html#coloring (close to the end of the section)
Also documented (long ago) here: https://mihai-nita.net/2013/09/12/color-logging-with-maven/

And a screenshot from a real console (not Eclipse):
![image](https://user-images.githubusercontent.com/1307726/198564711-19da1046-345e-4da7-9e2d-830c6306b8d4.png)

So what we see in Eclipse reflects that logback does by default in a real console, dark or not.

**Comment by mihnita** [comment]
Options:
* Declare "that's what logback does, works as intended" => not nice
* Blue is blue. All that the ANSI support can do is render it according to the configured palette.
  But the paletter is controlled by  the user, we can't really mess with it.
   And the ANSI support  has no way to tell that "hey, this blue comes from logback, let's treat it differently"
  So no help here.
  * The only fix that I can think of is to configure logback to use something other than blue for info
   There is a way to do that, I know I've seen it, but I can't find it now.
   We can try to do it dynamically, with different colors for dark / light modes.
   Or we can try to use a color that works for both modes.
   If we do this, the Eclipse console will not look like a real one. But it will be readable.

**Comment by mihnita** [comment]
Oups :-(

Found it, but it is not for logback, but for log4j2. It looks like this:
`%highlight{%5level}{FATAL=white, ERROR=red, WARN=blue, INFO=black, DEBUG=green, TRACE=blue}`

And this is where I've seen it: https://github.com/mihnita/ansi-econsole/issues/82 :-)

It looks like the only way to do it for logback is with a custom appender.

And I have something...:
https://github.com/mihnita/java-color-loggers
And in maven: https://mvnrepository.com/artifact/com.mihnita/color-loggers/1.0.7

This is the default output with my appender:
![image](https://user-images.githubusercontent.com/1307726/198569050-5f60ed1f-8458-4347-8cba-43075e8f039e.png)

But it can be configured, for example:
![image](https://user-images.githubusercontent.com/1307726/198570078-e7d9fc11-4331-485b-93c4-236de7a523f3.png)

The config file looks like this:
https://github.com/mihnita/java-color-loggers/blob/main/color-logger-logback/src/test/resources/logbackColorEscRegion.xml

You need to uncomment the `<errorColor> ... <traceColor>` and put there whatever ANSI escapes you want.

But that would require adding either a dependency on `com.mihnita:color-loggers`, or just extract the custom appender.

---

Note: the big vulnerability warning in Maven is scarry, but there is nothing in the artifact itself.
They are "Vulnerabilities from dependencies"
The artifact supports custom colors for jdk, log4j (the old one, 1.2), and logback.
And Log4j 1.2, which has the vulnerabilities and has no fix.

I thought about splitting it in 3 artifacts, one for each logger, but since nobody really uses it, it was low priority.

---

Anyway...
Probably a custom provider would be the easier option.
The code is trivial, 40 lines or so (https://github.com/mihnita/java-color-loggers/blob/main/color-logger-logback/src/main/java/com/mihnita/colorlog/logback/ColorPatternLayoutEncoder.java)

**Comment by mickaelistria** [comment]
Closed as reported fixed in https://github.com/eclipse-m2e/m2e-core/issues/1003#issuecomment-1290585542
