### ISSUE TITLE
Execute unkown mojos by default

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#1013]
Currently m2e works very "defensive" (compared to e.g. IntelliJ but people seem fine with that) as it only executes mojos that are known to be **enabled** by special m2e meta-data.

While in the past this might seems a good idea where software is not changing that much, I think today it becomes more and more unmanageable. New plugins are created every day, techniques arise and vanish faster than people can adapt.

I therefore like to propose the following more *graceful* approach:

1. If there is metadata, we do not change anything
2. If there is no meta-data we execute the mojo in a "sandboxed" mode that is we catch any errors that might occur when executing the mojo and then add a warning in the pom with a quickfix that allows the user to choose if the mojo should never be executed again or maybe retried later (e.g. after a change in the pom or project)
3. Additionally there could be a hint to **search** for specialized connector or **learn** about connectors and what value they bring

**Comment by kwin** [comment]
Just executing maven plugins in certain phases during incremental build could mean a huge overhead. I would rather stick with the default of not executing it but allow to enable execution even if the plugin doesn't have m2e metadata.

**Comment by laeubi** [comment]
> Just executing maven plugins in certain phases during incremental build could mean a huge overhead.

But at least that's what the user is requesting and expecting ... and if there are degradation then one could still disable it or add metadata to the plugin or even implement incremental build API. But we should not punish all plugins for some that "might be slow".

> I would rather stick with the default of not executing it but allow to enable execution even if the plugin doesn't have m2e metadata.

That's already the case and what m2e currently does. The problem is that it is just to complicated and users have no clue why/how this works and actually don't care.

**Comment by HannesWell** [comment]
> Just executing maven plugins in certain phases during incremental build could mean a huge overhead.

There is already a the `<?m2e ignore ?>` instruction (respectively a corresponding m2e lifecycle-mapping configuration), so if one wants to disable the execution entirely it is already possible. Or if it is actually wanted but not that often one can use  `<?m2e execute onConfiguration?>`.

Or we could measure the runtime and ask the user to ignore a plug-ins execution?

But as said in other discussions, one important point when executing mojos without a connector is to refresh modified files after the execution. One way to make m2e aware which files are affected we could add another parameter to the `m2e` processing instruction like `filesToRefresh` or alike.

Alternatively we could try out the approach suggested on the M2E mailing list to transform the class definitions to find all cases where files are modified. I have thought again about that suggestion and since we are loading each mojo and its dependencies (including maven core?) in an own PlexusContainer we probably only have to consider the cases from the Java standard library. We could instrument the mojo class files to collect all files that are created, deleted or modified and refresh them after the execution. I have not yet tried out anything about that, but at least to find modified files it could be managable solution that would work for many plug-ins without modification.
In general it would still be better if a mojo would use a Build-Context API for the reasons discussed (better error reporting, checking in the mojo if a file has changed, maybe even cancellation, etc.). However for mojos that don't do it and that should be executed by default, that is a tempting approach.

**Comment by laeubi** [comment]
We really should not transform any classes, this is too complex and error prone. If one is concerned about changed files, simply use a filewatcher or just refrehs the eclipse tree after mojo execution.

**Comment by HannesWell** [comment]
> We really should not transform any classes, this is too complex and error prone. If one is concerned about changed files, simply use a filewatcher or just refrehs the eclipse tree after mojo execution.


I tested the other suggestion from the Maven mailing list to use a Java NIO WatchService and it looks like (at least on Windows) this is really implemented based on events and not always polling the file-system and thus burning CPU-cycles and the file-system.
Does anybody of the Linux/Mac users know if that is the same for Linux/Mac?

We could then do the following to notice at least changes in the project directory. I think we should not consider any parent project because in cases of parallel builds sibling folders may be changed by other builders.

```
    IProject project = ...;

    Path projectBasedir = Path.of(project.getLocationURI());
    WatchService watchService = projectBasedir.getFileSystem().newWatchService();
    path.register(watchService, StandardWatchEventKinds.ENTRY_CREATE, StandardWatchEventKinds.ENTRY_DELETE,
        StandardWatchEventKinds.ENTRY_MODIFY);

    // execute the mojo

    WatchKey watch = watchService.poll();
    if(watch != null) {
      for(WatchEvent<?> watchEvent : watch.pollEvents()) {
        Path changedFile = (Path) watchEvent.context(); // relative to watched path
        IFile file = project.getFile(org.eclipse.core.runtime.Path.fromOSString(changedFile.toString()));
        file.refreshLocal(IResource.DEPTH_ZERO, null);
      }
    }
```

**Comment by mickaelistria** [comment]
No need to add m2e-specific behavior for that. Eclipse Workspace allows to auto-refresh projects on changes, using a WatchService as well IIRC. Window > Preferences > General > Workspace > Refresh using native hooks or polling.
When it was implemented, I believe implementation of WatchService was still polling on Windows or mac; but was already event-based on Linux. It's very likely things have improved since then.

**Comment by szarnekow** [comment]
Java20 will likely get a non-polling watchservice on mac. Cannot link the openjdk bug right now since the bugtracker is undergoing maintenance (yes, that's apparently still a thing 🤔 )

**Comment by kwin** [comment]
FTR: https://github.com/openjdk/jdk/pull/10140#issuecomment-1301796837

**Comment by HannesWell** [comment]
> Java20 will likely get a non-polling watchservice on mac. Cannot link the openjdk bug right now since the bugtracker is undergoing maintenance (yes, that's apparently still a thing 🤔 )

Thanks for that hint.

I checked https://github.com/openjdk/jdk/blob/4dbebb62aa264adda8d96a06f608ef9d13155a26/make/modules/java.base/Java.gmk and it looks like only macosx and aix are using the default `PollingWatchService`. Consequently I assume that for other OS a real event-based watch-service is used.
I suggest to check if the actually used `WatchService` is an instance of `PollingWatchService` (just compare the class name) and disable the automatic refresh then (and notify the user about that). Polling the FS for large workspace would probably be a huge performance regression.

**Comment by guw** [comment]
> When it was implemented, I believe implementation of WatchService was still polling on Windows or mac; but was already event-based on Linux. It's very likely things have improved since then.

Mac still polling

**Comment by laeubi** [comment]
For the refresh part I have now created:
- https://github.com/eclipse-platform/eclipse.platform/issues/299

**Comment by laeubi** [comment]
I'll use the camel project as a reference here (as it already served good purpose in improve import speed) for example camel API has currently the following mappings:
![grafik](https://user-images.githubusercontent.com/1331477/211147935-9a42be33-b413-4d48-add5-552c273be5b9.png)

So the first step would be here:

1. error should be replaced by "automatic". error itself is misleading anyways as since a while we only **warn** about missing connectors
2. then there should be a preference settings what automatic means: `execute` (default), `ignore` and probably `error`
3. depending on the setting we can then show a green, yellow or red icon
4. it would be good to have a way to change the mapping here as this seems the most user-centric way and even if the view is hidden by default, we should better document that it exits and is easier to use than editing the XML or find the corresponding execution in the pom.

**Comment by laeubi** [comment]
Screenshot with automatic mappings:
![grafik](https://user-images.githubusercontent.com/1331477/211154172-484634e1-48af-459b-b25c-bb68b31b00c4.png)

**Comment by laeubi** [comment]
It seems that my initial idea of having an explicit "automatic" action is not really useful and just makes it more confusing for the user, I therefore removed that again and replaced this by a single setting what should happen on unknown executions, where "execute" is the default:

![grafik](https://user-images.githubusercontent.com/1331477/211298610-0fa92418-246a-4377-913a-60d02d63013b.png)

**Comment by laeubi** [comment]
Related issue for this is:
- https://github.com/eclipse-m2e/m2e-core/issues/1189

**Comment by laeubi** [comment]
Another related issue:
- https://github.com/eclipse-m2e/m2e-core/issues/1190

**Comment by HannesWell** [comment]
At least for my m2e-workspace the builder went wild since this change on my Windows computer and was constantly building on full speed forever.
After I disabled the workspace-preference `Refresh using natives hooks or polling` the situation improved. The builder is still building repeatably but only in greater intervals (about every ~5/10s), but this already happened before #1181.

So my guess is that if a mojo-execution changes some files in a project the automatic workspace-resources refresh detects that a few moments later and triggers a new incremental build. Therefore I think we should really find a way to detect which files where changed during the mojo execution and refresh those within the m2e-builder execution for a mojo. Then hopefully the workspace-resource manager considers this as a change issued by the builder, which hopefully calms down the builder.

**Comment by laeubi** [comment]
Can you share an example project to reproduce this? I think this is more a general problem then because the build output is not stable/reproducible (e.g. contains a timestamp in a a generated file) and thus would generate the same behavior anyways. but previously unnoticed.
Another reason would be that we are triggering builds on wrong events (e.g. timestamp changed but not file content) see:
- https://github.com/eclipse-m2e/m2e-core/issues/1047

**Comment by laeubi** [comment]
This is done now, if anything is left it could be handled with more specific issues.
