### ISSUE TITLE
Build and Test with GitHub Actions on Windows and Mac OS

### ISSUE THREAD

**Issue by kwin** [eclipse-m2e/m2e-core#1080]
Currently some tests fail on those OS which makes the life for contributors using one of those OS really hard.

This is related to #1046.

**Comment by HannesWell** [comment]
Enabling a GH workflow to run on Windows should not be a problem.

My concern about also running verification builds on Mac is that Mac-Runners are ten times more expensive with regards to our CI minutes and Windows is already twice as expensive as Linux:
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers

I'm not sure if we have the usual 2000min per month or if the EFN made a good deal with GH so that we have more. But if we only have 2000min per Month and assume we would build on Linux, Windows and Mac and the build takes about ~15min, each run costs us (1+2+10) *15min = 195min, so we have only about ~10 builds per month for master and PR builds.

@laeubi for Tycho the build pipeline takes much longer and I assume we exceed the default 2000mins per month there. Did you know if anyone bought more minutes? Or do we just get more?

**Comment by HannesWell** [comment]
And of course the Mac build would have to work first, but I cannot ensure that.

**Comment by laeubi** [comment]
SWT uses mac runners as well and I have not yet seen any restrictions here and I'm quite sure no one pays for it...

**Comment by laeubi** [comment]
I think this is more applicable:
https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration

> GitHub Actions usage is free for standard GitHub-hosted runners i**n public repositories**

**Comment by HannesWell** [comment]
> I think this is more applicable: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
> 
> > GitHub Actions usage is free for standard GitHub-hosted runners **in public repositories**
> 

Reading that I think I understand it wrong all the time. Thanks for that hint.
Looks like the limit of free minutes only applies to private repos in free accounts. 
> For private repositories, each GitHub account receives a certain amount of free minutes and storage for use with GitHub-hosted runners, depending on the product used with the account

Then there is no reason to not build+test on macOS as well. It can't be slower than Windows...
I updated the PR. @kwin then it would be your turn to fix the failing tests. :)

**Comment by HannesWell** [comment]
@kwin can you please try to debug the test-failures on macOS?
With the latest M2E you can put a break-point at the failing test code and just have to add the property
[debugPort](https://tycho.eclipseprojects.io/doc/latest/tycho-surefire-plugin/test-mojo.html#debugPort) e.g. with value 8000 to the `m2e-core--build` launch config and RUN it. Then the build should stop the test execution at your break-point.

Btw. are you sure your clean-up in https://github.com/eclipse-m2e/m2e-core/pull/1079 did not break the tests?

**Comment by HannesWell** [comment]
M2E is now also built and tested on Windows as of https://github.com/eclipse-m2e/m2e-core/pull/1163.
