### ISSUE TITLE
M2E wrongly uses enforcer requireJavaVersion to configure projects

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-m2e/m2e-core#1099]
Since https://github.com/eclipse-tycho/tycho/pull/1740 all the classpaths in Tycho use Java 17 on my machine. That's clearly wrong, at least these 2 projects had other settings before (and they use specific other source/target values in their POMs):
![grafik](https://user-images.githubusercontent.com/406876/204556556-6b93940c-040c-463b-b3a8-123313bfba83.png)

I have Java 8, 11, 17 in my workspace preferences and I have all necessary EE levels mapped in the workspace preferences.

**Comment by HannesWell** [comment]
This is a bit strange. IIRC the `StandardVMType/`-classpath entries for those projects were the same when I tested it.
But now it is java-17 for me as well.

I hope this isn't another regression from https://github.com/eclipse-m2e/m2e-core/pull/981.
Will look into this in the next days.

**Comment by HannesWell** [comment]
While analyzing the problem I noticed that Tycho in general and therefore the projects you mentioned have a maven-enforcer-plugin execution with a `requireJavaVersion` rule configured:

https://github.com/eclipse-tycho/tycho/blob/3098bd215d5be0b8b00cd3e87bc35f4d1463d5be/pom.xml#L446-L448


Since in the properties section `<min.jdk.version>17</min.jdk.version>` is configured the build has to be performed with Java-17 and therefore I think M2E does everything right when it sets the JRE_CONTAINER to Java-17.
Please add your remarks to https://github.com/eclipse-m2e/m2e-core/issues/842#issuecomment-1336268152, if you think this is a false assumption.

**Comment by Bananeweizen** [comment]
To my understanding the requireJavaVersion rule is meant to clarify the version of the JVM that Maven itself runs on. It does not say anything about the source, target or other compiler/testing/runtime related Java levels of the modules being worked on.
See https://github.com/apache/maven-enforcer/blob/master/enforcer-rules/src/main/java/org/apache/maven/plugins/enforcer/RequireJavaVersion.java

**Comment by kwin** [comment]
> It does not say anything about the source, target or other compiler/testing/runtime related Java levels of the modules being worked on.

Neither does the underlying JRE Library do that, that is configured separately in the Eclipse JDT Compiler settings.

The reason why m-e-p configuration is evaluated is that it is pretty common that you don't use toolchains, but still do cross-compile (i.e. with Java11 produce Java8 bytecode). If here only a JRE8 would be set, then calling Maven from within Eclipse would use that JRE by default (and fail if any of the plugins require a newer JRE).

I agree that on the long term it would be good if m2e would establish a separate configuration for the JVM used to run Maven (but currently this is the project's JRE system library).

**Comment by reckart** [comment]
I'm using Maven with:
* the toolchains plugin and compiler source/target properties to ensure compatibility with Java 1.8
* the enforcer plugin to ensure that the Maven process runs at least on Java 11 because I use the maven-bnd-plugin which requires Java 11

The annoying thing is that since m2e now looks at the enforcer plugin instead of the compiler target means that in Eclipse, stuff is compiled against Java 11 and not against Java 8 as the toolchains/compiler properties indicate.

Please, it would be great if you could switch back to the old behavior.

**Comment by HannesWell** [comment]
Please try the latest m2e release to verify that the issue is fixed as expected:
- Latest: https://download.eclipse.org/technology/m2e/releases/latest
- Pinned: https://download.eclipse.org/technology/m2e/releases/2.2.0/
