### ISSUE TITLE
Bug 530587 - Maven Extensions in .mvn folder are ignored

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#116]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=530587

**Comment by laeubi** [comment]
I investigated a bit here, one problem is that the maven cli uses a magic [maven.multiModuleProjectDirectory](https://stackoverflow.com/questions/29778262/what-is-maven-multimoduleprojectdirectory-used-for) property to guess the root/location of a multi module build. In the context of m2e no such thing exists as far as I can tell (we only have a global `IMaven` instance).
There is `org.apache.maven.execution.MavenExecutionRequest.setMultiModuleProjectDirectory(File)` but I can't find it is used somewhere in m2e nor maven.

What I can think of is that we enhance the `org.eclipse.m2e.core.MavenPlugin.getMaven()` to accept a project/path/resource/... and we bubble up the hierarchy to find a .mvn folder for it and create a separate IMaven for those where an .mvn folder is present.

Otherwise we might need to consider adding/removing extension components on execution but I'm not sure if this works well. Is there a document describing how m2e works internally? Do we only execute one execution request at a time or could the run concurrently per project?

**Comment by laeubi** [comment]
Another approach I could think of is that we can handle this at creation time of the execution request.  But there are also some (deprecated) things that might not fit there especially in the area of lookups that actually would require to know the extensions so maybe that won't fit much.

Whatever we choose here, I really wonder how "costly" in the sense of memory and time to have several PlexuContainer. Should we avoid creating new containers a much as possible as it take considerable time? Are they take a considerable amount of memory? Can we maybe balance this a bit by keeping at least a (configurable?) number of containers?

**Comment by laeubi** [comment]
Requires
- https://github.com/eclipse-m2e/m2e-core/issues/546

**Comment by laeubi** [comment]
I think we can close this as *basic* support for extensions is there, and we would now need more specific tickets like 
- #118 

to further improve this.

**Comment by mickaelistria** [comment]
Yes, that's a good way forward, and it's great that we can say m2e now has (some) support for .mvn; it's a major achievement!
