### ISSUE TITLE
M2Eclipse gets stuck in endless update loop

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#123]
This has been reported in the following Bugs but its unclear how to reproduce this yet:

- https://bugs.eclipse.org/bugs/show_bug.cgi?id=558317
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=567959
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=553432
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=558689
- https://bugs.eclipse.org/bugs/show_bug.cgi?id=563140

**Comment by DieterMai** [comment]
I closed ticket Bug 563140 [1] since no longer reproducible

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=563140

**Comment by HannesWell** [comment]
Is there any progress on this issue? I run into it in my Tycho-Dev workspace (provisioned using the Tycho Oomph-Setup), using Eclipse-for-Commiter latest (currently at 2021-03) and m2e 1.17.2.

I sampled my Dev-Eclipse using VisualVM and from this it looks like the loop is in the LifecycleMappingFactory.

![grafik](https://user-images.githubusercontent.com/44067969/113278366-253dbf80-92e2-11eb-85bb-ee184590ddcf.png)

**Comment by laeubi** [comment]
@HannesWell Good idea. The problem is that this not occurs always, sometimes it helps to update one or two projects. then it works for some time and then comes back. I'm currently also again caught in an endless circle :-1:

**Comment by HannesWell** [comment]
Yes this issue just appeared recently to me. I could make it work once by updating one or two projects as you said. But now this also did not work. It is just terribly annoying, I can hardly change a line of code in my Tycho-Dev workspace.

Anyway. I just attached a debugger and my first impression is that the `DependencyResolutionContext` passed to the `ProjectRegistryManager.refresh` method gets always new elements added when `refreshPhase2` is called. But I will investigate further.

**Comment by laeubi** [comment]
ProjectRegistryManager line 504 a new facade is created but I can't tell from the code if this is intentional.

**Comment by laeubi** [comment]
@mickaelistria can you take a look at this? even worse now my IDE constantly get stuck and I need to kill the process :-(

**Comment by laeubi** [comment]
One think that might help here:
If I understand the code right, it triggers some kind of "project changed", maybe it would be better to just note all projects that require such a change event in a list, complete the cycle and then trigger one big "project(s) change" event afterwards?

**Comment by HannesWell** [comment]
Now that I used my Tycho-Dev workspace from an Eclipse instance that is launched (in debug mode) from another Eclipse having the m2e projects in its workspace the endless loop is gone. Even when I use the workspace from the `standalone` Eclipse again.

When I just hat the debugger attached I observed that constantly pom-files are added to the `DependencyResolutionContext context` in the very end (line 607) of `ProjectRegistryManager.refreshPhase2()` by calling `context.forcePomFiles(...)`. Since the calling method runs in a loop while `context` is not empty this would explain the endlessness. 

```
    Set<RequiredCapability> oldRequirements = newState.setRequirements(pom, requirements);
    if(originalRequirements.containsKey(pom)) {
      oldRequirements = originalRequirements.get(pom);
    }
    // if our dependencies changed, recalculate everyone who depends on us
    // this is needed to deal with transitive dependency resolution in maven
    if(oldCapabilities != null && hasDiff(oldRequirements, requirements)) {
      for(Capability capability : oldCapabilities) {
        context.forcePomFiles(newState.getVersionedDependents(capability, true));
      }
    }
```
From the relevant code snippet above I concluded that the pom files are only added to the context if `hasDiff(oldRequirements, requirements)` is true. When I looked into the elements of both sets I noticed that they contain the same artifacts but with different versions. Some were Tycho `2.2.0` some were `2.3.0` and some were `2.4.0-SNAPSHOT` (not necessarily mixed in one set but in different hits of the same break-point).
This also coincides with my observation that the endless loop first occurred for me when I fetched and rebased the commits for the Tycho 2.3.0 release from the Tycho git repo. So the modules in my workspace went from `2.3.0-SNAPSHOT` to `2.3.0`, to `2.4.0-SNAPSHOT`. Maybe m2e does not update the project-data correctly and holds some old version strings.

But this is the first time I look into the sources of m2e so this might be the wrong path.

Similar to @laeubi's suggestion I thought that the DependencyResolutionContext should also hold a second set of already refreshed/handled poms in order to avoid the endless loop. Nevertheless the root cause of the endless loop should be found because it seems to work before/sometime.

**Comment by mickaelistria** [comment]
I don't think I'll be available to work on this issue soon (no more school for my kid here, so reduced productivity and another kid to get born sometimes this month making me off from work for one month); but it's definitely something I'm interested in seeing fixed.
What I have missed the most so far are steps to reproduce from a simpler project. If someone can identify some steps, that would be help in making more concrete progress.
The current depedency resolution in m2e is not immune to build cycles as far as I know. As a consequence, if Tycho has some build cycle it can make things fail. I don't think Tycho has a build cycle but Tycho x.y.0-SNAPSHOT usually builds some parts with Tycho x.y-1.0-SNAPSHOTs, so if versions are ignored or erroneous as suggested by @HannesWell , then it can create a cycle and make resolution fail.

**Comment by laeubi** [comment]
The problem is that the error comes and goes and when its gone there is normally no demand to broke it again ... my hope is, that maybe someone with more knowledge of this resolving stuff can give a hint or has an idea what could be the issue so for example so its easier to try out for people having the issue than starting from scratch. But I can of course understand that this is not a top-issue as long as it is not reproducible.

What would be of major interest for me would be: How good is this area covered by unit test? So if I start hacking on his, how big is the chance to break something unintentionally and uncovered?

**Comment by HannesWell** [comment]
Mickeal then all the best for your family.

A reproducible case would indeed be a goo thing. I deleted and re-provisioned my tycho-workspace a few days ago because of this problem and run again into the endless loop (I think it was after going back and forth in the git history between and after the 2.3.0 release). So I can try to find steps to reliably reproduce this issue.

Regarding cycles in the build path: Sometimes I get problem markers indicating cycles in the build path. The last time the vanished by cleaning and building the entire workspace so maybe this was based on outdated metadata that cause the same problem here.

**Comment by laeubi** [comment]
For the tycho case I was able to break the cycle by:

1. kill all background work (needed to go to prefrences > show systemsleeping and system operation)
2. select tycho-core project > Update Maven Project
3. Now the endless build is gone but I haven't yet tried to update all maven projects

**Comment by laeubi** [comment]
Below there is an extract from the log, while for some times there are some items different after a while the following entries are repeated over and over again:

```
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/tycho-metadata-model: org.eclipse.tycho:tycho-metadata-model:2.4.0-SNAPSHOT with classifier  to /tycho-metadata-model/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/tycho-embedder-api: org.eclipse.tycho:tycho-embedder-api:2.4.0-SNAPSHOT with classifier  to /tycho-embedder-api/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/org.eclipse.tycho.embedder.shared: org.eclipse.tycho:org.eclipse.tycho.embedder.shared:2.4.0-SNAPSHOT with classifier  to /org.eclipse.tycho.embedder.shared/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/org.eclipse.tycho.core.shared: org.eclipse.tycho:org.eclipse.tycho.core.shared:2.4.0-SNAPSHOT with classifier  to /org.eclipse.tycho.core.shared/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/tycho-lib-detector: org.eclipse.tycho:tycho-lib-detector:2.4.0-SNAPSHOT with classifier  to /tycho-lib-detector/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Using org.eclipse.m2e.jdt.JarLifecycleMapping lifecycle mapping for MavenProject: org.eclipse.tycho:sisu-equinox-launching:2.4.0-SNAPSHOT @ /home/christoph/git/laeubi/tycho/sisu-equinox/sisu-equinox-launching/pom.xml.
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/tycho-core: org.eclipse.tycho:tycho-core:2.4.0-SNAPSHOT with classifier  to /tycho-core/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/org.eclipse.tycho.p2.tools.shared: org.eclipse.tycho:org.eclipse.tycho.p2.tools.shared:2.4.0-SNAPSHOT with classifier  to /org.eclipse.tycho.p2.tools.shared/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/org.eclipse.tycho.p2.resolver.shared: org.eclipse.tycho:org.eclipse.tycho.p2.resolver.shared:2.4.0-SNAPSHOT with classifier  to /org.eclipse.tycho.p2.resolver.shared/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/sisu-equinox-embedder: org.eclipse.tycho:sisu-equinox-embedder:2.4.0-SNAPSHOT with classifier  to /sisu-equinox-embedder/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/tycho-metadata-model: org.eclipse.tycho:tycho-metadata-model:2.4.0-SNAPSHOT with classifier  to /tycho-metadata-model/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/tycho-embedder-api: org.eclipse.tycho:tycho-embedder-api:2.4.0-SNAPSHOT with classifier  to /tycho-embedder-api/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/org.eclipse.tycho.embedder.shared: org.eclipse.tycho:org.eclipse.tycho.embedder.shared:2.4.0-SNAPSHOT with classifier  to /org.eclipse.tycho.embedder.shared/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/org.eclipse.tycho.core.shared: org.eclipse.tycho:org.eclipse.tycho.core.shared:2.4.0-SNAPSHOT with classifier  to /org.eclipse.tycho.core.shared/target/classes
10.04.21, 06:32:55 MESZ: [INFO] Resolving P/sisu-equinox-api: org.eclipse.tycho:sisu-equinox-api:2.4.0-SNAPSHOT with classifier  to /sisu-equinox-api/target/classes
```

I then cancel the job and if I update the 'org.eclipse.tycho:sisu-equinox-api' for example as a singel project it works.

After that I got to Maven > update project, deselect all projects and use "add out of date" then everything works fine. So this seems to happen if

1. All or a set of problematic projects are out of date (this happend for me after switching branches for example)
2. m2e automatically (or manually) tries to update the projects

**Comment by laeubi** [comment]
I now get an error marker:
Description	Resource	Path	Location	Type
`The project cannot be built until its prerequisite tycho-core is built. Cleaning and building all projects is recommended	sisu-equinox-launching		Unknown	Java Problem`

but the tycho-core project has no error markers and I have performed a project->clean all

**Comment by laeubi** [comment]
This also happens for other projects, interestingly from time to time the maven builder kicks in and begin to build something (without any action that would trigger this, e.g I just switching some editor windows). Now the error marker on org.eclipse.tycho:sisu-equinox-api' is gone but remains on other projects. SO it seems there is something stuck or timmed-waiting in m2e

**Comment by cpfeiffer** [comment]
We recently experienced such a loop as well.
We have configured maven-jar-plugin to generate a `MANIFEST.MF` with the current timestamp (see the `<Build-Time>` element).
```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>${version.maven-jar-plugin}</version>
        <configuration>
                <archive>
                        <manifestEntries>
                                <X-Git-Revision>${X-Git-Revision}</X-Git-Revision>
                                <X-Git-Branch>${X-Git-Branch}</X-Git-Branch>
                                <Maven-Version>${project.version}</Maven-Version>
                                <Deployment-Version>${Deployment-Version}</Deployment-Version>
                                <Maven-Artifact>${project.groupId}:${project.artifactId}</Maven-Artifact>
                                <Build-Time>${maven.build.timestamp}</Build-Time>
                                <Implementation-Version>${project.version}</Implementation-Version>
                                <Implementation-Vendor>${project.organization.name}</Implementation-Vendor>
                        </manifestEntries>
                </archive>
        </configuration>
</plugin>
```

In eclipse, we have the https://github.com/tesla/m2eclipse-mavenarchiver connector installed, that takes care of generating the manifest in eclipse.

So when a project changes, we get the following chain:
```
org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.mavenProjectChanged
-> org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.isLifecycleMappingChanged
  -> org.eclipse.m2e.core.project.configurator.AbstractCustomizableLifecycleMapping.hasLifecycleMappingChanged
    -> org.eclipse.m2e.core.project.configurator.AbstractProjectConfigurator.hasConfigurationChanged
```
The last method `hasConfigurationChanged()` compares the previous configuration with the current configuration, which include the concrete timestamps for the manifest. The timestamp's precision is 1s.

So whenver the file gets generated (which triggers a change event leading to the above chain) and the processing takes more than one second (or occurs around the switch to the next second), `hasConfigurationChanged()` returns `true` and triggers another build. Ad finitum.

The fix for us is to add a profile with a maven-archiver configuration that uses a hardcoded, stable timestamp instead of the actual time. We activate this profile only inside m2e.
```
<configuration>
    <archive>
        <manifestEntries>
            <Build-Time>20210101235959</Build-Time>
        </manifestEntries>
    </archive>
</configuration>
```

**Comment by mickaelistria** [comment]
Thanks Carsten. Do you think you could provide a minimal reproducer? Also do you see an opportunity for improvement here in m2e (for example keeping finer grain timestamps in memory and compary per nano or milliseconds instead of seconds to avoid loops, or just replacing some `<=` by `<` )?

**Comment by cpfeiffer** [comment]
I can try to create a reproducer. However I'm not sure how m2e could avoid such a situation. I was mostly trying to document the problem so that others can check their setup for a similuar situation.

A greater precision (e.g. ns or ms) would make the problem even worse since the `Build-Time` in the manifest would change even more quickly and thus the project would be built more often.

A lower precision (e.g. min) would help a bit, but still would lead to uneeded builds. IMHO, the Manifest should never change in eclipse, as long as the the code/metadata for it doesn't change. Because every change triggers a build.

I actually need to check the `X-Git-xxx` properties whether they cause unnecessary builds after doing a commit.

**Comment by rotty3000** [comment]
Hey All, this was troubling me deeply and we had a bug open for this on [osgi/osgi-test](https://github.com/osgi/osgi-test/issues/406) and we thought it was in our side (perhaps in bndtools).

However, I finally tracked it down to a loop between `org.eclipse.core.internal.events.AutoBuildJob` job and `org.eclipse.m2e.jdt.internal.DownloadSourcesJob`:

- the download job runs and finds source artifacts which appear to be out of date so are queued to be downloaded (because their timestamp is older than the main artifact) however the maven resolver (which is asked to download the artifact) thought differently and decided it didn't need to download it. But nevertheless, the download job thinks there are new files and so asks the classpathcontainer to update which triggers the build job
- immediately, while the download job has yet to totally finish, the build job runs (due to the updated classpathcontainer) but gets cancelled because `autoBuildJob.isInterrupted()` returns true since it detects the conflicting download job and is cancelled.

The problem is the issue with the two different checks for the source artifact: **one by m2e code**, and the other by **maven.resolver** that have different ideas about what is out of date which means the download queue is always refilled with the same files over and over and so it just loops.

HOWEVER, I was able to trigger the issue *at will* by _changing the timestamp directly on the file system of the source artifacts for any dependency referenced by the build_.

So, if you really want to eliminate the problem without searching every individual timestamp in your `.m2` that might be out of order like so:
```bash
osgi]$ ll --time-style=full-iso org.osgi.test.junit4/1.0.1/
-rw-rw-r--  1 rotty rotty 16341 2021-08-05 10:34:56.000000000 -0400 org.osgi.test.junit4-1.0.1.jar
-rw-rw-r--  1 rotty rotty  8078 2021-08-05 10:34:42.000000000 -0400 org.osgi.test.junit4-1.0.1-sources.jar
```
run something like: `find ~/.m2/repository -type f -name "*-sources.jar" -exec touch {} +`

**Comment by HannesWell** [comment]
Thanks for your analysis!
It sounds like it is connected to #252, but just from your description I'm not certain if the solution for #252 is sufficient. Just to make sure, do you use the latest m2e release version `1.18.2` and does your method to reproduce the issue with that version as well?

**Comment by rotty3000** [comment]
I have only checked `1.18.1.20210618-2246` and as you mention had noted that the logic around this had changed. So I will update and retest as soon as I get a chance.

**Comment by rotty3000** [comment]
The issue appears not to be reproducible against the 1.18.2 release. Nice work!

**Comment by kjsmita6** [comment]
Seems to be fixed for us on 1.18.2 as well.

**Comment by bgooren** [comment]
I can confirm that it is fixed for me too after upgrading to 1.18.2. Thanks!

**Comment by priyankabishnoi** [comment]
No Its not. I tried with 1.18.2 and 1.18.3 the loop goes on and on for the test bndrun project

**Comment by mickaelistria** [comment]
> No Its not. I tried with 1.18.2 and 1.18.3 the loop goes on and on for the test bndrun project

Can you please provide exact and detailed steps to reproduce?

**Comment by priyankabishnoi** [comment]
When i try to update my maven project then I have one project which is for OSGI Test . When the update for that project starts then i see that the loop keeps going to 61% and then back to 60%.
What i see that the build is trying to so some cleaning because of which it goes back in percentage and then again move up to 61%.
This keeps going

I tried just now that if i uncheck the checkbox to Clean the project during Maven Update Project then the project updates fines. this never used to happen this way before,

Also i am stuck on one more thing. I have the OSGI test bnd run . When i try to launch it in eclipse it tries to find the dependencies in bnd cache folder rather than .m2. I am totally stuck because of this issue now.

**Comment by priyankabishnoi** [comment]
I cannot share the project. But i gave you the steps

**Comment by mickaelistria** [comment]
Sorry, those steps are not enough for me to reproduce easily. Please consider creating a minimal project that can be used to reproduce the issue and that you can share.

**Comment by mickaelistria** [comment]
It may also be related to #155 which was recently fixed and replaced O(n^2) builds by O(n) in some cases.

**Comment by laeubi** [comment]
I captured a stack trace for the case where the whole IDE is stuck and I have to kill the process.

[stack.txt](https://github.com/eclipse-m2e/m2e-core/files/7795536/stack.txt)

This happens often when an endless build cycle is running and I use quick-fix to extract a variable or something similar.

**Comment by mickaelistria** [comment]
@laeubi Did you identify some steps to reproduce or other particular conditions that made this freeze appear?

**Comment by laeubi** [comment]
I noticed that it helps to only update the tycho-core project to break the cycle, and then update some other projects step-by step. It seem to happen when switching between branches but I haven't found a good reproducer yet.
Maybe it is even caused by (not) installing a connector for some of the maven goals, or because I'm building on the commandline as well while having Eclipse open...

The freeze itself is sadly rather reproducible , if the endless loop happens, I cancel it but it starts whenever I edit (and save) a file. If I then forget to cancel this in certain situations (e.g. STRG+1 -> extract to local variable) it freezes.

So I have to cancel the build after each save to not get accidentally stuck.

**Comment by laeubi** [comment]
Just as for today I synced with master and now the endless build cycle is back ... anything you want me to do? 

1. I start the IDE
2. Change a file and the update begins stuck at roughly 50% in the progress view with no visible progress saying project <projectname> and project names are repeating after some time.
3. I select something that could be extracted into a local variable, CTRL+1->Extract to local variable->Return
4. Job progress freeze, the IDE is no longer responsive, everything is froozen
5. I can only press the close button and my OS (debian) suggest to forcibly terminate the application.

**Comment by lordyavin** [comment]
[m2e-locked-threaddump-1642599131305.tdump.txt](https://github.com/eclipse-m2e/m2e-core/files/7897500/m2e-locked-threaddump-1642599131305.tdump.txt)

**Comment by laeubi** [comment]
From my experience with that it still happens with the latest m2e, but I seem to get it working almost always with the following steps:

1. Update tycho-core
2. then run an update that updates everything else

I don't know how the update-cycle behaves currently, but maybe it is using some kind of Map/Set with unstable sorting that causes issues here?
Maybe a solution would be to fetch the set of projects to update and build a tree that updates the "roots" first and then climbs up to any project depending on this and so on.

**Comment by laeubi** [comment]
By the way it seems the progess view was enhanced with more details and I now see a constant loop saying 

1. Building
2. Building (Canceled)
3. Building (Sleeping)
4. Building and so on

I also see a Job that says "Refreshing Workspace)

**Comment by MKuettner** [comment]
I have the same issue (since last update to Eclipse 2022-03). For me this is a real blocker and currently makes the whole IDE unusable. 
Only workaround is to close nearly all projects or to disable "Build Automatically".

**Comment by olivergg** [comment]
@MKuettner which version of m2 do you use ? Have you tried with 1.20.1.20220227-1319 ?

**Comment by zachpn** [comment]
@MKuettner: I had the same issue. Uninstalling "M2E PDE Integration" resolved the update/build workspace loop.
I am using the same M2E version as olivergg posted.

**Comment by MKuettner** [comment]
I use following versions:
M2E - Maven Integration for Eclipse (includes Incubating components): 1.20.1.20220227-1319
M2E - PDE Integration: 1.20.0.20220208-0831

**Comment by kjsmita6** [comment]
I am occasionally having this issue using m2e 1.20.1.20220227-1319 on Eclipse 4.23 but the problem seems to be much better (i.e. doesn't block the entire IDE). When it happens, my progress view still shows alternating jobs between "Building" and "Downloading Sources/Javadoc". But like I said, it is not a huge problem as it was before.

https://user-images.githubusercontent.com/9405706/163262012-4275dcf3-2966-45a7-a9d5-4b0f76bce191.mov

(goes on forever)

This screen recording is from my Eclipse 4.23 while running our RCP application (from an Eclipse launch config). This does not happen in the RCP application itself. 

From previous comments, is it a problem with m2e/pde? Our RCP app does not have m2e/pde (or any PDE for that matter) but my Eclipse 4.23 does.

**Comment by laeubi** [comment]
With the latest version I see the following being stuck and running over and over again with different projects but never making any progress:
![grafik](https://user-images.githubusercontent.com/1331477/164958610-9937db44-2c3e-4f1d-bc32-6c57c8c1b07f.png)

Maybe this gives a hint about what is being the root cause: https://github.com/eclipse-m2e/m2e-core/discussions/619#discussioncomment-2621807

**Comment by guw** [comment]
So this looks like some kind of event flooding. Is the builder triggering async resource changes, which are propagated outside of the builder?

**Comment by laeubi** [comment]
I'm now having a workspace where the problem occurs and I can debug it from what I see the problem is that there is one parent project that has errors, thus it don't make it into the ProjectRegistry and then if another project tries to fetch that project is is noticed that it is out of date and needs updates, then it is noticed that the project itself has changed and needs an update and so on....

**Comment by laeubi** [comment]
In refreshPhase2 there is:

```
 for(Capability capability : changedCapabilities) {
      context.forcePomFiles(versionedCapabilitiesOnly ? newState.getVersionedDependents(capability, true)
          : newState.getDependents(capability, true));
    }
```

this adds "dependents" pom files to the context, which leads to that the queue never gets empty here... (from what I can see).

**Comment by laeubi** [comment]
I have a fix for this, just need to think if we maybe can do better than my first simple approach ...

**Comment by laeubi** [comment]
I can confirm, after getting the stuck again with an older m2e release, that with the new code now it is correctly detected and the cycle is left after one initial improvement of the build cycle.

**Comment by HannesWell** [comment]
> I can confirm, after getting the stuck again with an older m2e release, that with the new code now it is correctly detected and the cycle is left after one initial improvement of the build cycle.

That's great news and a good reason to go for M2E 2.0 :)
Thanks for your work.

**Comment by ahoehma** [comment]
Hi guys ... happy new year to all.

I just found this issue here ... my eclipse shows similar symptoms.
Have 2 projects open in workspace. Both have many maven plugins configured, jaxb, aspectj etc.
After "update projects" (without clean) ... the progress hangs forever in "Resolve plugin dependency".
But no more details, no m2e console log, nothing in "Maven Workspace Build".
How can I get more logging for m2e processing?

Is it worth to create an issue for that? Would be hard to provide a project to reproduce that because of closed source :(

**Comment by laeubi** [comment]
> Is it worth to create an issue for that? Would be hard to provide a project to reproduce that because of closed source :(

Without any reproducing test-case the only thing you can setup a dev environment and debug it yourself. Alternatively you can contact me to enter a contract for analyze / fix it for you and I can sign a NDA or similar.

**Comment by ahoehma** [comment]
@laeubi is it possible to enable more logging etc ... and how? please give me a hint. I would like to see something like "resolving foobar for plugin blubs" ... somewhere is a endless loop or something.

**Comment by laeubi** [comment]
You can open the "Maven Console" to get the maven log but I doubt this will give you more insights of the problem.

**Comment by reckart** [comment]
I often have a similar problem when importing a new existing maven project into the workspace. After a couple of tries of killing Eclipse and retrying, it usually works. Also, what seems to help me is to disable auto-build before importing the project. IMHO it is very different from the endless build loop that is described in this bug (and which I also had experienced at various points in the past).

**Comment by ahoehma** [comment]
@reckart my current scenario is more about hanging after trigger an update for already imported projects. I have a little feeling that its maybe something deep inside the artifact-resolving specially for "invalid" artifacts, timeouts while talking with nexus etc. Not sure if this is already in the code... but it would be good to have some properties to pimp timeouts etc. to force "hard crashes" here and there to see more clearly where the real cause is. Endless loops and killing eclipse is really ugly. But I imagine its really complex stuff inside m2e :)

**Comment by reckart** [comment]
I didn't try it yet, but if you can consistently reproduce the issue, you might try firing up VisualVM and use the CPU sampler to check in which part of the code the hang occurs.

**Comment by u023871** [comment]
This bug seems to have returned in 2022-12. In 2022-09 it was fine!

**Comment by laeubi** [comment]
> This bug seems to have returned in 2022-12. In 2022-09 it was fine!

Reproducerin test-case?

**Comment by u023871** [comment]
Wow you are fast. Test case is hard to describe... Only wanted to check whether this is a known issue.

Maven console is going wild after 
- right click project
- Maven
- Update project...

and the process never stops.

The project has 33 modules.

The info in lower right corner all the time tells you "Updating Maven Project: (XY%)", with percentage changing.

You can also see that memory consumption is very high (up to 4G at the moment, will monitor whether it comes to an OOME), but also frequently changing.

Maven console is writing tons of lines... and does not stop.

**Comment by u023871** [comment]
Ok the more I read the original posted comments and links, the more I seem to have a different issue.

I can indeed stop the build process and do not need to kill the Eclipse process.

But of couse this does not help me, as my project is not built anymore...

Will try deleting and importing cleanly... maybe there was an issue converting the old project config files to the new version...

**Comment by u023871** [comment]
@laeubi Ok meanwhile my MacBook crashed, got obviously too hot with 2 Eclipse instance endlessly trying to build (tried 2 different project versions in order to exclude issues with our own code - but at least 1 of them was completely developed on the old 2022-09). Additionally I noticed some increased memory consumption, which rose up until 5.5G before I stopped it. Also I missed that indeed the Eclipse instances do not exit on closing them, in case a Maven build is running and although I pressed the red square button, and indeed need to be killed. However, I have a suspicion... Upgraded lombok agent a few days ago, will downgrade again and retest - although I already worked with that setup for a few days, very weird...

**Comment by u023871** [comment]
Hi!

After I still had the same issues with our project with updates from 2022-09 to or even fresh installations of Eclipse 2024-03 with m2e core 2.6.0, I stumbled over these m2e release notes, allowing to disable automatic builds for single projects:

https://github.com/eclipse-m2e/m2e-core/blob/master/RELEASE_NOTES.md#project-preference-for-automated-maven-project-configuration-updates

> Project preference for automated Maven project configuration updates
Automatic configuration updates for Maven projects can now be disabled the in the project preferences. This allows to disable these updates individually per project and to store the setting in a preference-file under version control, which is useful for projects that require special workspace configuration that doesn't exactly match the configuration in the pom.xml.

However, this option is also available as global Maven settings in Eclipse preferences.

After disabling it globally, the endless loop Maven build issue is gone :-)

Most probably I will have to manually update the Maven project in Eclipse now after pom.xml changes, but at least we can upgrade our project to Java 21 now (which was not supported by 2022-09).

Just wanted to share...
