### ISSUE TITLE
Investigate removal of com.google.guava

### ISSUE THREAD

**Issue by rgrunber** [eclipse-m2e/m2e-core#1288]
It looks like Guava is only used in a few spots, so it would be nice if this dependency could be removed.

```
org.eclipse.m2e.editor/src/org/eclipse/m2e/editor/mojo/MojoParameterMetadataProvider.java:import com.google.common.cache.Cache;
org.eclipse.m2e.editor/src/org/eclipse/m2e/editor/mojo/MojoParameterMetadataProvider.java:import com.google.common.cache.CacheBuilder;
org.eclipse.m2e.editor/src/org/eclipse/m2e/editor/mojo/PlexusConfigHelper.java:import com.google.common.reflect.ClassPath;
org.eclipse.m2e.editor/src/org/eclipse/m2e/editor/mojo/PlexusConfigHelper.java:import com.google.common.reflect.ClassPath.ClassInfo;
org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/MavenProjectCache.java:import com.google.common.cache.CacheBuilder;
org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/MavenProjectCache.java:import com.google.common.cache.CacheLoader;
org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/MavenProjectCache.java:import com.google.common.cache.LoadingCache;
org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/MavenProjectCache.java:import com.google.common.cache.RemovalNotification;
```

Not sure if some other dependency, or Java standard library itself might provide a comparable solution, but if so, it would be great to reduce dependencies (at least for m2e.core).

**Comment by laeubi** [comment]
It was removed and it was then added back, so the main point is, what do we gain if we remove it (beside that less dependencies are always better) ...

**Comment by mickaelistria** [comment]
> what do we gain if we remove it 

More room for complex bugs in project cache :P

**Comment by rgrunber** [comment]
> > what do we gain if we remove it
> 
> More room for complex bugs in project cache :P

Fair enough. My motivation was partly that at ~3MB and given JDT-LS + m2e are barely using it, it would have been nice to reduce the size of the runtime, but doing a quick look through cache solutions shows people either using Guava, or writing their own. May as well stick to Guava for now, or re-open if this ever changes.

**Comment by HannesWell** [comment]
I replaced guava's cache with a standard Java solution a while ago, but it caused issues https://github.com/eclipse-m2e/m2e-core/issues/924 and was therefore re-introduced in https://github.com/eclipse-m2e/m2e-core/pull/928.

The standard Java solution was obviously not perfect, but as noted in https://github.com/eclipse-m2e/m2e-core/issues/924#issuecomment-1256032691 I believe the mentioned issue can be fixed without using guava's cache, since our use is actually not too complex.

I didn't have a strong need to get rid of Guava, but as already noted I think it would be nice to have. So if you are interested I would be open to replace Guava's cache again and review a PR with an enhanced standard solution. Ideally in conjunction with a test-case that reproduces the cause in #924, fails with the old 'standard-Java' solution (just reverting #928) and does not fail with an enhanced one.

**Comment by akurtakov** [comment]
For the record - JDT LS is been used in cloud environments and this ~4MB of guava multiplies by thousands or even more in some cases. 
This comment is just for the sake of clearly stating the gains for m2e downstreams but as long as no better solution is developed by anyone so be it.
P.S. I even remember the multiple extra CVE fixing releases done few years ago exactly for guave but this seem to not have happened lately.

**Comment by akurtakov** [comment]
The information is here, interested people have the data incl. project priorities, all info is public - my job is done here ;) .

**Comment by fbricon** [comment]
If you want to get rid of Guava but still use a powerful cache library, you can use https://github.com/ben-manes/caffeine (~740kB jar). API is similar to Guava's.
