### ISSUE TITLE
[regression] MavenExecutionContext.execute(MavenProject, MojoExecution, IProgressMonitor) loses the MojoExecution configuration

### ISSUE THREAD

**Issue by fbricon** [eclipse-m2e/m2e-core#1304]
In https://github.com/eclipse-m2e/m2e-core/blob/d5c25f953b047d96d9ede34c3722a44fe8dfa3cf/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/embedder/MavenExecutionContext.java#L329, the mojo execution's clone is incomplete, so the original configuration is not copied over the clone. This nasty regression breaks invocations of custom mojo executions, as used in m2e-wtp (https://github.com/eclipse-m2e/m2e-wtp/issues/23)

**Comment by laeubi** [comment]
@fbricon can you probably test if just copy over of the config would fix the issue?

**Comment by fbricon** [comment]
It does work, but I'm trying to understand why the clone was needed in the first place, how that relates to resources:resources failing when a .mvn folder exists (#1150)

**Comment by laeubi** [comment]
Can you then please open a PR @HannesWell wants to prepare a new release due to other regressions as well and if its easy to mitigate we should include this, everything else can be done/investigated later.

The problem is that mojo executions previously where created and cached but they use the "global" maven context. In that case a wrong classloader is used for them and that then fails (best shown by using a `.mvn` folder)
