### ISSUE TITLE
M2E connector for build-helper-maven-plugin no longer triggers a refresh of project after adding the source

### ISSUE THREAD

**Issue by ctubbsii** [eclipse-m2e/m2e-core#1333]
In Eclipse 2022-12 and earlier, when I imported a project using the build-helper-maven-plugin to add an additional (generated) source directory, that directory's classes were immediately accessible by the other files, which compiled fine.

Now, in Eclipse 2023-03, when I import the project, I get an error that a class in the added source directory cannot be resolved for an import statement in a class that is in the regular src/main/java directory. When I go to the class, and have Eclipse try to import the class, it detects that it is already available (in the same package), so it doesn't actually do anything, but the error message goes away.

So, I then tried just "cleaning" all projects (it's a multi-module project) immediately after importing and the error message also went away that way.

It seems that any refreshing of the project will resolve the error. But, the error still exists when the project is initially imported.

To reproduce, simply import the main branch of the https://github.com/apache/accumulo project as an existing Maven project.

**Comment by kwin** [comment]
This is probably an issue for https://github.com/tesla/m2eclipse-buildhelper/ as m2e natively does not support that Mojo.

**Comment by snjeza** [comment]
@ctubbsii You can try to add
```
"java.configuration.maven.defaultMojoExecutionAction": "execute",
```
to your settings.json.

**Comment by kwin** [comment]
This issue is not about execution of some Mojo from within Eclipse, but about a dedicated project configurator which evaluates these execution configurations. This cannot be done from within the Maven plugin jar, but needs to be performed by a native Eclipse plugin.

**Comment by glhez** [comment]
Since I got the same issue than @ctubbsii  with source folder that I created to split source code (`src/main/java` and `src/test/java` is not enough) the problem arise with [build-helper-maven-plugin][1] which contains a [lifecycle-mapping-metadata.xml][2] (and [m2eclipse-buildhelper][5] is probably no longer required).

There are globally two cases:

1. The source folder already exists: in my case, I add additional src/test source folder to split some code. The additional source folder are ignored unless you spam F5 or Alt + F5.
2. The source folder does not exists or is generated as part of the build; in these cases, a prior mvn clean install is required _but_ the maven plugin add an inexistent source folder which trigger an error in the Java Source folder page in Eclipse. I think that's the case mentioned in @ctubbsii  case => [his example][4] is referenced something that look like it was generated. 

I have both case in our project.

Before switching to 2023.03, this worked fine. 

[1]: https://www.mojohaus.org/build-helper-maven-plugin/
[2]: https://github.com/mojohaus/build-helper-maven-plugin/blob/master/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
[3]: https://github.com/mojohaus/build-helper-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/buildhelper/AddSourceMojo.java#L63
[4]: https://github.com/apache/accumulo/blob/main/pom.xml#L1578
[5]: https://github.com/tesla/m2eclipse-buildhelper

**Comment by ctubbsii** [comment]
@glhez wrote:
> There are globally two cases:
> 
> 1. The source folder already exists: in my case, I add additional src/test source folder to split some code. The additional source folder are ignored unless you spam F5 or Alt + F5.
> 2. The source folder does not exists or is generated as part of the build; in these cases, a prior mvn clean install is required _but_ the maven plugin add an inexistent source folder which trigger an error in the Java Source folder page in Eclipse. I think that's the case mentioned in @ctubbsii  case => [his example](https://github.com/apache/accumulo/blob/main/pom.xml#L1578) is referenced something that look like it was generated.
> 
> I have both case in our project.
> 
> Before switching to 2023.03, this worked fine.

The folder seemed to exist by the time the project finished importing into Eclipse, but it was just ignored. So, I think my experience was closer to the first case you mention, and I didn't see an error about the directory being non-existent. The error was just an import error because it seemed to be ignoring the recently added directory. We use build-helper to add source directories twice in our project. The first one is the example you linked, which adds a source folder with a non-standard name, but always exists (just used to organize code). That seems to work fine. The second place we use this is [where we generate/create a source directory](https://github.com/apache/accumulo/blob/main/core/pom.xml#L286-L325) as filtered resources. This does exist by the time the build-helper plugin is created, but is created in the `target/` directory by the  That's the directory that seems to be ignored until a refresh or clean.

**Comment by laeubi** [comment]
About the missing resource folders, this is a problem of m2e only adding them if they are there at the time of project update, I'm currently working on a fix here:
- https://github.com/eclipse-m2e/m2e-core/pull/1354

**Comment by laeubi** [comment]
I have imported the mentioned project in the latest m2e snapshot and it shows no errors after initial project import so I assume this as being fixed, it also does not required any extra connector to be installed.
