### ISSUE TITLE
Cannot resolve dependencies from private maven repo from WSL

### ISSUE THREAD

**Issue by jdneo** [eclipse-m2e/m2e-core#1357]
Below is comment from user, The original issue is here: https://github.com/microsoft/vscode-java-dependency/issues/746

I've no idea why it's not working. Would be helpful if some detailed reproduce steps can be provided.

The steps I did were:
- Install WSL2, Ubuntu
- Configure Maven and JDK in WSL
- Configure the settings file in WSL, with data from my private repository, where my dependencies are
- Clone any project that has dependencies that only exist in my private maven repository.
- run the MVN clean install command on WSL. In this step, the execution is successful, that is, the dependencies were identified during the execution

With these steps I ensured that WSL was correctly configured with Maven and the JDK.

After this:
- Open VSCode via WSL.
- Opened the project that I cloned in WSL
- With the project open, the dependencies that only exist in my private repository, are not identified and marked with error in VSCode.
- To ensure that everything was correct, I opened the vscode terminal (on the same window that already had the project open) and, through this terminal, executed the command mvn clean instal. The command was executed successfully.

Following all these steps, I conclude that the configuration in WSL is correct, is something missing in VSCode.

In VSCode, I set the maven settings path correctly. I put the path where it is stored in WSL

_Originally posted by @felipemmasan in https://github.com/microsoft/vscode-java-dependency/issues/746#issuecomment-1514814184_

**Comment by laeubi** [comment]
> Open VSCode via WSL.

This is a **Eclipse Plugin,** it has nothing to do with **VSCode** so you must open the issue with whoever is providing support for VSCode / Maven.

**Comment by akurtakov** [comment]
VSCode plugins are using m2e under the hood to import the projects. 
@jdneo Can you reproduce the issue in Eclipse? Please note that most of us are not familiar with VSCode (and some not even with Windows access) so the report as it is right now is practically non-actionable. If you can come up with m2e test case to show the issue that would make is possible to understand what the problem you face is.

**Comment by laeubi** [comment]
> VSCode plugins are using m2e under the hood to import the projects.

Thats possible but nothing in the report indicates anything related or reproducible with m2e, e.g. 

> In VSCode, I set the maven settings path correctly

is something hardly we can influence / check.

Next is

> Install WSL2, Ubuntu

I never had seen people to install Eclipse in WSL (why?) so I suspect that this is also quite VSCode specific

So I really think this should be reported to the VSCode plugins first.

**Comment by mickaelistria** [comment]
I'm reopening this issue as it is a valid one and there are contributors (at least myself and @akurtakov and @fbricon ) willing to provide some support if possible. However, I agree with @laeubi that in the current state of m2e, it would be best to try to also provide a reproducer involving Eclipse Workbench + m2e.

> So I really think this should be reported to the VSCode plugins first.

In the initial report, I read "Originally posted by @felipemmasan in https://github.com/microsoft/vscode-java-dependency/issues/746#issuecomment-1514814184"

@laeubi I think you're missing some context: @jdneo is a maintainer of vscode-java and very active contributor to JDT-LS , many of the people who are active on those projects also had good technical interactions with him and his report or answers are often very accurate and helpful.
I think it's really worth giving a chance to this issue. Asking for details is fine, but closing it immediately is not great regards towards the community.

**Comment by laeubi** [comment]
> I'm reopening this issue as it is a valid one and there are contributors (at least myself and @akurtakov and @fbricon ) willing to provide some support if possible. 

That's great to hear, but I still don't think it is valid without any indication (e.g. debuging) to claim its a problem of m2e, even in the referenced issues it is reported as "working now":

- https://github.com/microsoft/vscode-java-dependency/issues/746#issuecomment-1521090454

> In the initial report, I read

 I can fully understand if it was debugged and maybe some problematic code was identified or at least a stacktrace is supplied, with a note that it was discovered _in the context_  of that report, but why copy the original report which is completely VSCode specific? That's why I don't see in the current state how it could be solved/investigated in the context of m2e at all, especially as using a private repository (e.g. Nexus mirror) is more a standard than an exception, so if there would be a general problem it would be hopefully already be discovered. Also it is completely unclear what WSL should have to do with that, m2e neither requires WSL nor has it anything to do with resolving dependencies...

The only thing I could guess is that for "VSCode via WSL" one might need to be patient regarding the usage of pathnames (e.g. Windows uses `\` what is often used as escape character and needs to be doublequoted while linux uses `/`) but then this is nothing really in the context of _m2e as a library_.

So I still think this has to be investigated either on the VS Plugin Code side or on the JDT-LS, or whoever calls m2e code there and if that shows there is a bug/possible improvement in m2e a specific report with what is expected should be created.

**Comment by jdneo** [comment]
Close as the original issue has been solved.
