### ISSUE TITLE
[BUG] Discover m2e connector's "Finish" button doesn't work

### ISSUE THREAD

**Issue by olkornii** [eclipse-m2e/m2e-core#1371]
Steps to reproduce:
1. File -> Import -> Maven -> Existing maven project
2. Select maven project (ex. [maven-wrong-project]) -> click Finish
3. Discover m2e connectors appears -> click "Resolve All Later" -> Finish -> nothing happens, no errors in error log

[maven-wrong-project]: https://github.com/eclipse/reddeer/tree/master/tests/org.eclipse.reddeer.eclipse.test/resources/org/eclipse/reddeer/eclipse/test/m2e/core/ui/wizard/maven-wrong-project

**Comment by laeubi** [comment]
I have looked into this and its a bit strange as m2e tries to determine if the issues are "handled" before it allows to finish the wizard, but in fact I can't find any case where it is not valid to finish the wizard (even though in this case it is equivalent to cancel the wizard), I therefore will remove the check as it is already implemented badly by simply doing "nothing" instead of inform the user what to do.

**Comment by olkornii** [comment]
@laeubi I've tried and still does not work for me with Eclipse 2023-06-R.
