### ISSUE TITLE
m2e is missing dependency

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#1520]
I try to update an existing install of m2e (using https://download.eclipse.org/technology/m2e/snapshots/latest/)

but it fails with:

`No repository found containing: osgi.bundle,javax.interceptor.api,1.2.2`

**Comment by laeubi** [comment]
@merks any idea how I can find out how this is exactly pulled in?
The dialog is not very informative, In the error log I see an entry after expanding a lot of stuff:

`Missing requirement: M2E Embedded Maven Runtime (includes Incubating components) 3.9.400.20230822-2330 (org.eclipse.m2e.maven.runtime 3.9.400.20230822-2330) requires 'osgi.bundle; com.google.guava 32.0.1' but it could not be found`

so it is actually `org.eclipse.m2e.maven.runtime` > `com.google.guava` > `javax.interceptor.api` ?

**Comment by merks** [comment]
Generally when I see an error like `No repository found containing: osgi.bundle,javax.interceptor.api,1.2.2` it tells me that while there is a repository with the metadata but no artifact repository for it could be found.  I.e., the message comes form org.eclipse.equinox.internal.p2.artifact.repository.ArtifactRequest.getResult().  That typically happens because p2 has properly loaded the latest content metadata but not the latest corresponding artifact metadata.  Also, the server tends to serve stale stuff for a while, even when the actual update site has been updated.  

When that happens, I generally hit it with a big hammer (Clear Cache...):

https://github.com/eclipse-platform/eclipse.platform.ui/issues/1051#issuecomment-1689414567

If you don't have Oomph installed, a restart might help, otherwise you're stuck clean caches yourself...

Hopefully that helps...

**Comment by laeubi** [comment]
@merks this is a bit "special" as we pull in stuff not build by P2 but `bnd-maven-plugin` so it *could* happen that there is missing stuff not included in the updatesite (as we have not enabled include *all* dependencies), but of course it would be good to find out what dependency is actually pulling that requirement.

**Comment by merks** [comment]
I see that bundle is definitely not available at that site, but it's not clear which other sites were available during resolution...

**Comment by laeubi** [comment]
Hm... I'm a bit confused, lets say I have an update-site that only contains one bundle, then the metadata will still list requirements but this does not mean all requirements are in the artifacts right? "No repository found containing" is (as far as I know) caused because one has "contact other update sites during install" but then again there is no gurantee that there is *any* site that contains this that's why I think m2e should provide it, *if* m2e require it somehow, but as there are a lot of other stuff (wwd, lsp4, leminx...) I was curious what dependency actually *wants* this and didn't find any clue in the error log like:

"X requires javax.interceptor.api but it could not be found anywhere"

**Comment by merks** [comment]
FYI, I'll be away from the computer for a few hours with only my iphone, so that will make it harder to help...

**Comment by merks** [comment]
Good to see the problem solved.

**Comment by laeubi** [comment]
I hope so :-)
