### ISSUE TITLE
How to open open m2e-core project in vanilla eclipse?

### ISSUE THREAD

**Issue by cal101** [eclipse-m2e/m2e-core#153]
# ** Ticket is on hold while official documentation is updated.**

# ** ATTENTION TO THE CASUAL READER**
# This is currently only documenting my current attempts of getting the m2e project into eclipse.
# The commands work on linux only and if you don't know what you are doing you may loose data.
# You have been warned.

Things about building and hacking m2e are in the flow currently.

I want to try to write a short but complete list of steps needed to load most of or hopefully full m2e-core project
into a vanilla eclipse installation + workspace.
That should be useful for writing or updating the real documentation later.

Please scroll to the bottom for next steps missing and add comments how to proceed.

## Current state

Some projects loaded, not building yet.

## setup build environment
```
# setup build environment
mkdir -p m2e-core-env

# download and install maven
(cd m2e-core-env; wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz; tar xfz apache-maven-3.6.3-bin.tar.gz)

# setup environment with java 11 and up-to-date maven
export JAVA_HOME=/usr/lib/jvm/openjdk-11
PATH=${JAVA_HOME}/bin:${PATH}
PATH=${PWD}/m2e-core-env/apache-maven-3.6.3/bin:${PATH}
```

## clone repo
```
# clone repo
git clone https://github.com/eclipse-m2e/m2e-core.git
cd m2e-core
```

## Install/reinstall eclipse (can be repeated)
```
# install/re-install vanilla eclipse jee
rm -rf ../m2e-core-env/eclipse
tar -C ../m2e-core-env -xf ../eclipse-jee-2021-03-R-linux-gtk-x86_64.tar.gz
```

## Reset workspace (can be repeated)
```
# make sure working copy is on master and clean
git fetch --all
git checkout .
git clean -fdx
git checkout -B master origin/master
```
## Start eclipse with clean workspace
```
# start eclipse with fresh workspace
rm -rf /tmp/eclipse-workspace
# select /tmp/eclipse-workspace as workspace
../m2e-core-env/eclipse/eclipse
```

## Import the project into eclipse
```
Import projects / Existing Maven Projects
    m2e-maven-runtime
    "Select Tree"

Import projects / Existing Maven Projects
    Import m2e-core 
    With sub projects
    Exclude
        m2e-core-tests

    Requester pops up: Setup Maven plugin connectors.
        Let all being selected and "Finish"
    Requester pops up: Install
        Let all (3) being selected 
        "Next"
        "Next"
        Accept License
    Requester pops up: Installing unsigned software
        "Install anyway"
    Allow restart of eclipse

```

**How to continue importing other projects?**

**Comment by mickaelistria** [comment]
Hi Carsten,

I'm working on changing those steps by addition of .target stuff and
target-platforms. I'll adapt the documentation as part of this story.
I'd suggest you just don't start writing documentation as this can become
outdated with the upcoming changes.

**Comment by cal101** [comment]
OK.
I started this issue based on the assumption that adding the .project files in PR 150 would solve most of the problems.
I added very rough .project/.classpath files myself back in january to be used for erefactor and that made m2e loadable
except for 4 or 5 projects that I ignored.
That made it possible to run the cleanups and rebasing the hack regurlarly worked well enough.
But I now wanted to target all projects and so my innocent question on the list.
Didn't expect all hell breaks loose ...

**Comment by laeubi** [comment]
@cal101 @mickaelistria I can only strongly recommend to try creating setup files instead of "commandline" instructions as these are highly platform dependent

just the very first step `mkdir -p m2e-core-env` will fail on windows completely. Also all those stuff about installing tools is normally not necessary, recent eclipse(-installer) includes everything that is required (java+embedded maven)

Also recommending recursive destructive commands like "rm -rf" are a real no-go IMO as one can easily destroy and potentially loose data (the same applies to git clean -fdx) without explicit notice for inexperienced users that state the danger here.

**Comment by cal101** [comment]
I never intended to add command line instructions to the official documentation.
I just prefer to document the real steps done to reduce "works for me" issues.

The style of the existing but outdated documentation is OK for me.
It's just outdated and left questions open for newcomers.

Nobody will start the first eclipse project with m2e-core.
Providing full setup files for that would be a waste of time IMO.

But nevertheless I added some warnings above.

**Comment by mickaelistria** [comment]
The main issues I see with this doc are
* Maven is not required to build/developer m2e
* Some documentation about plugin development should assume users are already familiar with plugin development and simply link to a general tutorial about plugin development, and then just add details about the part of the process that are specific to current project.
* reinstalling eclipse, resetting workspace... all that is not necessary, and I'd even say not recommended as it's not making people more productive.
* As mentioned earlier, using the Maven import is not going to provide the best result due to m2e using pom-less Tycho and m2e not yet supporting build extensions; a regular project import would work better

**Comment by cal101** [comment]
Seems like we are getting somewhere.
1. Maven is not required
2. maven  import is wrong, project import shall  be used.

Resetting workspace etc. is just for showing that i started fresh and making it reproducible.
It's just a clean setup for the import of the project.
That import is the most important part.
Only by documenting what I did you were able to pinpoint one mistake not  obvious  to me.
The m2e project providing maven integration to eclipse, which is build with maven
on the command line should NOT be imported as a maven project.
Progress made.

But I can happily wait for an updated documentation and test it when it's ready for testing.

**Comment by mickaelistria** [comment]
Actually, even Java is not required with EPP.
I've completed most of the changes I planned to improve the dev environment setup. Adding .project was a major piece of this work, adding .target files was another, but actually in many cases, one wouldn't even need to deal with m2e specific target and can just use their current IDE as TP. I tried to explain that in https://github.com/eclipse-m2e/m2e-core/blob/master/CONTRIBUTING.md#%EF%B8%8F-setting-up-the-development-environment . Feedback would be highly appreciated.

**Comment by HannesWell** [comment]
Using the running IDE is a not very reliable approach because your TP depend on your Eclipse installation. And as far as I can see m2e itself is not even required to develop m2e if one does not want to build it, is it? So this can cause trouble if you have plugins missing in your installation or use an old version.

Furthermore when using an Oomph-Setup you can use a modular target that allows to merge multiple Targlets into one aggregated target for the whole workspace. This way you can have multiple _Oomph-projects_ in the same workspace, for example m2e and Equinox-p2. Unfortunately the Oomph Targlets does not support the new Maven-type locations. I don't know if there are plans to support it (but it would be great).

**Comment by HannesWell** [comment]
For your information, the Oomph setup for m2e is now available in the `Eclipse-projects` catalog of the Oomph installer.
