### ISSUE TITLE
Embed and use Maven 3.8.1

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#159]
Maven 3.8.1 is released. m2e should include it.

**Comment by HannesWell** [comment]
This makes #3 outdated.

**Comment by vrubezhny** [comment]
@HannesWell  @laeubi Asking because you are the committers on this repository... Can anybody help creating a CQ for Maven 3.8.1 please? 
(The example of the CQ for Maven 3.6.3 can be found here: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21175)

For Maven 3.8.1:
Project/Source URL: https://github.com/apache/maven/tree/maven-3.8.1
The PR to update to embed and use Maven 3.8.1: https://github.com/eclipse-m2e/m2e-core/pull/189

Thanks in advance!

**Comment by vrubezhny** [comment]
@laeubi Thanks!

**Comment by vrubezhny** [comment]
The CQ #[23313](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23313) got successfully resolved.
