### ISSUE TITLE
Minimum Eclipse version for current versions of M2E?

### ISSUE THREAD

**Issue by TobiX** [eclipse-m2e/m2e-core#1699]
Hi,

I just tried to install M2E 2.6.0 on Eclipse 2023-03 (don't ask 😉), but it seems M2E requires org.eclipse.core.runtime 3.27.0 (which ships with Eclipse 2023-06 AFAICS) or newer since 2.5.0 (since #1608, to be precise). Was this change intentional? Is this documented somewhere?

**Comment by akurtakov** [comment]
The ultimate definition is what the project compiles against https://github.com/eclipse-m2e/m2e-core/blob/8789e4ca8878c4998f5dff159a8f9d5e2000ad77/target-platform/target-platform.target#L7 and it says Eclipse 4.30 (2023-12). With the scarce resources the project has (true for pretty much every FOSS project) supporting more than latest Eclipse release is beyond what we can do. Things might have worked before this change but they haven't been tested and verified in anyway. 
Speaking of the change itself it's fully intentional (details at https://github.com/eclipse-equinox/equinox/pull/228 ) .
Sorry for any inconvenience this is causing you but I strongly believe it's best for everyone if support is clearly limited to what we can do and try to drive the whole ecosystem forward.

**Comment by HannesWell** [comment]
> but it seems M2E requires org.eclipse.core.runtime 3.27.0 (which ships with Eclipse 2023-06 AFAICS) or newer since 2.5.0 (since #1608, to be precise). Was this change intentional? Is this documented somewhere?

The applied static [factories for `IPath` factories were introduced in Eclipse 2023-06](https://eclipse.dev/eclipse/news/4.28/platform_isv.php#ipath-enhancements) and therefore the corresponding bundle version is required.
In general, due to the nature how m2e is developed we are usually only definitively compatible to the previous and current Eclipse SimRel, every compatibility going back further is just by chance and might work or not.

**Comment by TobiX** [comment]
I understand completely. Thanks for the answer & for your great work. 👍

**Comment by laeubi** [comment]
> I just tried to install M2E 2.6.0 on Eclipse 2023-03 (don't ask 😉),

Why? (SCNR) :-)

As mentioned m2e is not only tested with latest Eclipse, it also often uses or requires the latest features as some are even added to the platform because of m2e demands, so you should try to stay up-to date if m2e is important for you.

Theoretically one *could* release for older versions, but this would defiantly require some dedicated effort from the ones that require this (e.g. sponsoring money or dev resources for backports and release engineering).
