### ISSUE TITLE
Only keep latest snapshot in local repository (Maven 3 timestamped snapshots)

### ISSUE THREAD

**Issue by rhoehener** [eclipse-m2e/m2e-core#245]
A very [old problem](https://stackoverflow.com/questions/4275466/how-do-you-deal-with-maven-3-timestamped-snapshots-efficiently), and we have been [working around](https://stackoverflow.com/a/17520790/1124509) it for decades.

I am aware that this is something that should be handled by Maven itself, and not m2e.

However, I do not see Maven changing this any time soon. It would be amazing if m2e could help make developer's life easier by providing such a feature. Maybe make it an option with a disclaimer.

I'd love to be able to finally ditch our custom plugins, scripts, tasks and services that do nightly cleanup of stale snapshots, in order to keep our disks from filling up.

**Comment by mickaelistria** [comment]
Sorry, but we won't put into m2e workarounds for Maven issues.
Contributing to Maven itself isn't much more complicated than contributing to m2e. So whoeven wants to see this issue fixed in m2e and feels capable of writing a workaround in m2e should instead consider contributing a fix to Maven itself; that will give better results and serve more widely.

**Comment by rhoehener** [comment]
Well, it was worth a try. Too bad really, I got my hopes up after reading this [comment of yours](https://bugs.eclipse.org/bugs/show_bug.cgi?id=528399#c3).

> Contributing to Maven itself isn't much more complicated than contributing to m2e

I don't know about the contributing part, but even if the Maven core decided to change this (which I doubt), it would be years before it made it into a release and then into the Eclipse embedded version.

> we won't put into m2e workarounds for Maven issues

Why not? Isn't this the very core of IDE's? Abstracting some of the complexities and deficiencies of the dev stack, thereby making it bearable and sometimes even a pleasure to work with?

**Comment by mickaelistria** [comment]
> it would be years before it made it into a release

That I don't know. It's up to Maven.

> then into the Eclipse embedded version.

We typically move m2e to latest m2e release in the following weeks or months. Definitely not a matter of years.

> Why not? Isn't this the very core of IDEs? Abstracting some of the complexities and deficiencies of the dev stack, thereby making it bearable and sometimes even a pleasure to work with?

No, an IDE is not a set of workarounds for upstream technologies. Workarounds are often more expansive to author and maintain than actual fixes in the proper layer, and deliver only a very minimal value to a subset of the ecosystem. We may allow workarounds only if the issue was reported upstream, no good solution is known at the moment, and the workaround is properly commented to be removed whenever upstream has the fix. But we should never start development by writing a workaround, that would drive to more expansive or lower quality in software in general.

**Comment by rhoehener** [comment]
I understand and agree that workarounds can lead to more complexity and more maintenance burden.

But, IDE workarounds can be a strong signal and driver for the underlying tools to change. E.g. I am very glad that some version control clients have no problem at all with working around limitations of the abstracted system.

Also consider that this policy can have a discouraging effect on potential contributors.
