### ISSUE TITLE
Target Editor renders Maven target locations using Object.toString()

### ISSUE THREAD

**Issue by sewe** [eclipse-m2e/m2e-core#373]
Noticed this with the latest snapshot (1.18.2.20211011-2139):

![content-location](https://user-images.githubusercontent.com/491981/137129668-ecc8bce2-c9bc-4523-90ab-d9f9135af25c.png)

Apparently, the _Content_ tab with _Group By: Location_ uses `Object.toString()` to render the `MavenTargetLocation` node. :disappointed:

**Comment by HannesWell** [comment]
@laeubi in case you take care of this label improvement, for the Definition tab I noticed that the element for the new multi dependency target starts with the number of dependencies:

![grafik](https://user-images.githubusercontent.com/44067969/137133704-afe37a04-7f6c-4473-b2b1-1f2f6d123f78.png)

While this mimics the natural language, personally I don't find it very nice as label. The small number is a bit lost between the icon and the remaining text and it also has the effect that those multi Maven-targets are always sorted to the top.

This is just a cosmetic label and of course everybody has a different taste. Nevertheless I want to suggest some alternatives and maybe we end with a better solution :)
- `Maven Dependencies - 3`
- `Maven Dependencies, count: 3`
- `Maven Modules - 3`
- `Maven Module Group with 3 Dependencies`

**Comment by laeubi** [comment]
Yeah the problem is that one can't derive a good name from the childs (I first though about something like `<id of first child>  and n more ...` but the ultimate solution would be to allow giving a name to a group ... I also have to check that this is not a limitation of PDE itself as you can see it only affects the Content tab and I fear that there is simply the label provider not adapting correctly.

**Comment by laeubi** [comment]
This is a bug in PDE see https://bugs.eclipse.org/bugs/show_bug.cgi?id=576630
