### ISSUE TITLE
No logging and JIBX Plugin not running

### ISSUE THREAD

**Issue by githubuser100007** [eclipse-m2e/m2e-core#404]
I have Eclipse 2019, with the M2E, and when I put a JIBX plugin in my pom.xml, it does nothing (when I run 'mvn package' it runs fine). I can't figure out why, since the logging is not happening either. I looked at the .plugins\** log file and there is hardly anything in there (I even set it to DEBUG and still nothing).

**Comment by mickaelistria** [comment]
Please first try with latest release.
Also, what's the expected behavior?You'd exepect m2e to run the plugin in the IDE and generate the code? If so, please look at how to configure your project to execute random plugin as part of the build in the Eclipse IDE: https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html#execute-plugin-goal

**Comment by githubuser100007** [comment]
Turns out it was the plugin management tags. They were missing.
