### ISSUE TITLE
Default to "compileScope" for Maven dependencies in Target editor

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#416]
I think the nomal case is that if I add a Maven library to the target platform that I would its dependencies included. If you agree, could you make the "Dependency scope" default to compile instead of empty?

cc @laeubi 

![image](https://user-images.githubusercontent.com/139910/144043799-7875c245-f7c0-4b54-afe2-2ebddb88e611.png)

**Comment by laeubi** [comment]
> I think the nomal case is that if I add a Maven library to the target platform that I would its dependencies included

Its a bit hard to guess if that's always the case, I think the best would be to keep this issue open and see if others give feedback about this.

**Comment by vogella** [comment]
AFAIK if I add a Maven lib to a Maven libraries, it also downloads by default its dependencies.  Also a lib without it dependencies can't be used so the user would have to manually add all dependencies or use this feature.

@HannesWell WDYT?

**Comment by laeubi** [comment]
> Also a lib without it dependencies can't be used

That depends on the context. A lib might have dependencies that are not used in all classes, the target might already provide  some of its dependencies and so on...

**Comment by HannesWell** [comment]
I think both use cases are valid. Besides Christophs example, not including dependencies can also be wanted if for example the dependencies are already in the TP, provided by p2-repo (e.g. Orbit). Because the BND-Lib Tools (which are usually used to generate the Manifest of Maven modules, either by m2e or e.g. the Maven Bundle Plugin) specify dependencies in form of `Import-Package` headers, this works even the providing bundle's symbolic name may vary.

But I also assume that users more often want to include all compile-dependencies. However not including dependencies is not uncommon. If we only consider what is used more often, we should change the default to `compile`.
Nevertheless I think choosing to not include dependencies by default is also a valid because it is the more defensive choice and users then have to opt-in to include dependencies and are more aware of what they are doing if they want to go big?
But I'm not sure which one is the better overall default. 

Independently of which default is chosen, I would like to suggest the following changes to raise awareness of what is happening:
- Use the value `none` in the UI and in a .target file to specify that dependencies should not be included. For backward compatibility `none` should be used if the `includeDependencyScope` attribute is absent. `includeDependencyScope="none"` is also more clear than an absent attribute.

- Change the selection-label from `Dependencies Scope` to `Include dependencies of scope` or similar, to make clear that it is about which dependencies should be included into that location. In the beginning I confused the attribute with the scope you assign to a dependency in a Maven-pom and wondered if I select test if the artefact itself or its dependencies would only be visible to test sources and what `provided` would mean for Eclipse projects? But I was obviously wrong. Maybe a explanatory tool-tip would also help (for the other selections/check-boxes too).

**Comment by laeubi** [comment]
> Use the value `none` in the UI and in a .target file to specify that dependencies should not be included.

One could use an empty value as well currently, the scopes map directly to the scopes in maven so I don't think its good to invent something special here.

Sadly the actual value was not considered before but I have fixed that in my latest PR so items with other scopes are actually filtered out (the resolver API is a bit clumsy in that area).

**Comment by laeubi** [comment]
I think we could at least provide a preference page to configure the defaults for:

- Missing OSGi Manifest
- Dependencies scope
- Include Artifacts Source

used in the wizard. @vogella do you like to provide a PR for this?

**Comment by HannesWell** [comment]
> > Use the value `none` in the UI and in a .target file to specify that dependencies should not be included.
> 
> One could use an empty value as well currently, the scopes map directly to the scopes in maven so I don't think its good to invent something special here.

With the other values I fully agree, but I think a `None` value is special enough that an exception is IMHO more valuable to make it more clear. Especially in the UI. I think an absent-value in this relative important aspect is not a good idea.

**Comment by laeubi** [comment]
As long as it results in an equally xml we can show different labels/hint/... in the UI

**Comment by HannesWell** [comment]
> As long as it results in an equally xml we can show different labels/hint/... in the UI

Even if it is just in the UI it would be IMHO more clear.

**Comment by laeubi** [comment]
I think this is somewhat obsolete now one could decide to include dependencies and if compile is the default...
