### ISSUE TITLE
Managed Version Info is missing in pom Editor

### ISSUE THREAD

**Issue by c-koell** [eclipse-m2e/m2e-core#437]
In Eclipse 2021-09 (m2e 1.18.1) a info is shown  if you hover over a dependency where the depndency version is managed.

Here is a example
![Managed-Version](https://user-images.githubusercontent.com/4134346/145417476-4fd3122a-01c4-429d-ac7c-5ade649798c6.png)

In the newest Eclipse 2021-12 (m2e 1.19) the info is missing if you hover over the dependency

**Comment by dkfellows** [comment]
The pieces of information that are missing are:
1. The version of the artifact.
2. The fact that the version of the artifact is managed.
3. The coordinates of the POM that is doing the management of the artifact.
4. A link to the POM doing the managing.

All of those are very useful to have.

The information that is now shown is distinctly less useful:
1. The artifact ID (name). Which is normally just what is shown right there in the place I'm hovering.
2. The artifact's brief description, which is cool but not actually useful since nobody really uses that for anything within the context of an IDE.

Also, the font is a _lot_ larger (at least on my screen; YMMV), making the popup obscure more of the stuff that it is describing.

**Comment by Kiiv** [comment]
Really miss that too ! Back to the legacy editor for now.

**Comment by mickaelistria** [comment]
Upstream issue is https://github.com/eclipse/lemminx-maven/issues/238

**Comment by Kiiv** [comment]
Any news on that ? Seems there is some commit on lemminx repo with a 0.7.1 release

**Comment by mickaelistria** [comment]
Have you tried the latest snapshots of m2e? This should now be available.

**Comment by Kiiv** [comment]
Hi ! I was trying right now :)
But it seems worst, my pom XML editor does not have syntaxic coloration or mouse popup over anymore :s It just look like a very simple XML editor. I still have tabulation at the bottom with dependencies and so on.

Versions :
  M2E - Maven Integration for Eclipse	2.2.0.20230217-1439	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
  M2E - POM Editor using LemMinX language server (includes Incubating components)	2.0.3.20230202-1631	org.eclipse.m2e.lemminx.feature.feature.group	Eclipse.org - m2e
  M2E - SLF4J over Logback Logging	2.1.1.20230106-1511	org.eclipse.m2e.logback.feature.feature.group	Eclipse.org - m2e

**Comment by mickaelistria** [comment]
> But it seems worst, my pom XML editor does not have syntaxic coloration or mouse popup over anymore :s I

Can you please open a new ticket about that new issue, sharing the content of your <workspace>/.metadata/.log file?

**Comment by Kiiv** [comment]
#1265
