### ISSUE TITLE
PDE integration requires the second page of the wizard (feature creation) even if the flag "Generate feature" is not selected.

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#457]
PDE integration requires the second page of the wizard (feature creation) even if the flag "Generate feature" is not selected.

![image](https://user-images.githubusercontent.com/139910/146330402-9bccfd35-90be-4e18-936f-d5c8af107bf7.png)

**Comment by laeubi** [comment]
Can you check if it help to check/uncheck the box (might be an update issue?) and probably provide a patch?

**Comment by vogella** [comment]
> Can you check if it help to check/uncheck the box (might be an update issue?) 

No it does not help.

**Comment by laeubi** [comment]
The problem is only when adding a new item. Here PDE do not actually uses the wizard that is supplied by the extension but only the pages see `org.eclipse.pde.internal.ui.shared.target.AddBundleContainerSelectionPage.createTargetLocationProvisionerNode(...).new AbstractBundleContainerNode() {...}.createWizard()`

I'll have to take a look if I can fix this...

**Comment by laeubi** [comment]
See

https://bugs.eclipse.org/bugs/show_bug.cgi?id=577861
https://git.eclipse.org/r/c/pde/eclipse.pde.ui/+/188942

**Comment by vogella** [comment]
Thanks, Christoph.
