### ISSUE TITLE
Maven target folder part of the Eclipse file search

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#489]
Maybe this is a configuration issue on my side but the target folder shows up in file search in Eclipse. Should the target folder not be marked as "derived" by m2e? Or should the tooling set the target folder to be excluded?

The following shows my manual setting:

![image](https://user-images.githubusercontent.com/139910/148956709-8c1beb92-2979-4f34-b81e-ef2910a4dbaf.png)

**Comment by mickaelistria** [comment]
The target folder is marked as derived in the project; however, if you have a depedency tree in your working, it's very probable that this same `child/target` folder from parent is not marked as derived.
We cannot assume all `target` folders are derived; however, Platform could be improved so that by default, if a folder is set as derived in a "child" project, it's also set as derived in the parent project. Or even better, discuss whether all resources from a child folder that exists as folder should be marked as hidden or even be fully filtered out.
Anyway, I think the best place where to fix this is in Eclipse Platform (and I'm pretty sure a bug about it already exists).

**Comment by vogella** [comment]
@laeubi I now noticed that the project were created before I installed M2E so that do not have the Maven project nature / builder assigned to them. I removed them from the workspace and imported them again but as the .project files already exists no new data was added. What is the recommended way to add the Maven nature to existing plug-ins?

**Comment by laeubi** [comment]
Right click `Configure > Convert to Maven Project` or something alike?

**Comment by vogella** [comment]
Thanks @laeubi converting the project works fine. I creates a pom (unnecessary for the pomless Tycho build) but after deleting this file, "target" is marked as derived. It adds the Maven build and nature but I assume their is no downsize to that in case no pom is found.

Should Eclipse top-level projects also be converted to Maven projects? I also face the issue that "target" is included my Eclipse platform workspace. My current "workaround" is to run "mvn clean" on the command line if this happens to get rid of the target content.

**Comment by laeubi** [comment]
@vogella m2e currently does not understand [polyglot](https://github.com/eclipse-m2e/m2e-core/issues/119) projects (and tycho-pomless is a ployglot extension).

Sadly there is currently no way to mark a folder persistently as derived via configuration see [Bug 577639](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577639).

If you this is crucial to someones business an likes to speed up the development in that area a [sponsoring](https://github.com/sponsors/laeubi?frequency=one-time) would allow me to assign more time-slots on this.
