### ISSUE TITLE
POM Editor (Lemminx-based) formatting options - tabs and spaces

### ISSUE THREAD

**Issue by harbulot** [eclipse-m2e/m2e-core#498]
(This was mentioned as a comment in issue #458.)

The old POM editor was using the XML Editor formatting options, so we were able to choose between tabs and spaces and set the number of spaces.

![image](https://user-images.githubusercontent.com/80994/149761611-f6bd8cd6-8292-4dec-bffd-9c720da62df3.png)

Following the links from [the Lemminx project](https://github.com/eclipse/lemminx) leads to this document: https://microsoft.github.io/language-server-protocol/specification#textDocument_formatting

It seems a number of options are available, including `tabSize` and `insertSpaces`. It's not clear whether the new editor can make use of them, whether they can be set up from a graphical preference option or a configuration file.

**Comment by mickaelistria** [comment]
Please report this to the Wild Web Developer project which deals with common XML stuff used by m2e POM Editor using LemMinX.

**Comment by harbulot** [comment]
@mickaelistria Thank you. It looks like you'd mentioned this in eclipse/wildwebdeveloper#139.

More specifically (if anyone encounters this issue), the new editor seems to pick up the settings for tabs and spaces in _General -> Editors -> Text Editors_:

![image](https://user-images.githubusercontent.com/80994/149767187-67377ece-a6c1-4e43-b19b-930c43932e8e.png)

**Comment by LorenzoBettini** [comment]
Especially the "Displayed tab width" (e.g., 4) influences the number of inserted spaces, I seem to understand. I want 2 spaces for XML editors. If I set it to 2, then also the tabs in Java editor are displayed with 2 spaces. Most of all, if I change this setting, this will influence also Java editors to insert spaces instead of tabs, which I don't want... am I missing something?
