### ISSUE TITLE
Migrate m2e-tycho to m2e

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#605]
Now that we have m2e containing some PDE integration, and that a CQ was approved for m2e-tycho ( https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23882 ), it would probably make sense to migrate m2e-tycho directly into m2e.

**Comment by laeubi** [comment]
If I understand correctly the plugin actually does not adds much, it has a `<lifecycleMappingMetadata>` (what might probably better be part of tycho itself?) and it adds the PDE nature to imported projects.

It also do something with the classpath/launching but I'm not sure if this is actually necessary.... Do I miss something?

**Comment by mickaelistria** [comment]
@laeubi  I have thought the plugin had some connectors but I didn't investigate so I trust you there. If the plugin has no real payload and things can better be done in Tycho directly, then I'm all for it.

**Comment by laeubi** [comment]
I'm using tycho mostly with pomless so I can't really judge if/how much value the plugin adds for "pom-based" tycho projects.
I think the most important one is about the executions not creating warnings/errors and the rest _might_ already be obsolete. Also from our past discussions I remember you said it should "just work" if we support extensions (even it seems there are explicit code to disable tycho if m2e is in the properties...)

**Comment by mickaelistria** [comment]
>  I remember you said it should "just work" if we support extensions

I probably said that, but it doesn't mean I verified it ;) It sounds more like a hopeful statement or a goal than an assertion about the current state.

**Comment by gayanper** [comment]
With the tycho m2e plugin not released to support m2e 2.0, its not possible to import maven tycho projects such as eclipse plugins into Eclipse IDE

**Comment by HannesWell** [comment]
The tycho-m2e connector is not necessary anymore. As of Tycho 2.7.4 all Tycho plug-ins have M2E lifecycle-mapping metadata embedded that tell M2E that their execution can be ignored. In the IDE Eclipse PDE does, what Tycho does during builds.
So even if you are using an older version of Tycho, you can simply ignore those missing connectors.

**Comment by laeubi** [comment]
@HannesWell one thing I can think of that might be a problem (but haven't tested yet) is that if you have no `.project` file and import a pure `pom.xml` then might the PDE nature missing for such project?

**Comment by gayanper** [comment]
Yes thats what I’m trying to do. The projects doesn’t have the .project and .classpath files. The tycho m2e extension actually have configurators to handle it.

**Comment by HannesWell** [comment]
> Yes thats what I’m trying to do. The projects doesn’t have the .project and .classpath files. The tycho m2e extension actually have configurators to handle it.

What packaging-type do you have specified in the pom of those projects? Is it `eclipse-plugin`?
Because unlike for example if you have packaging-type `bundle` in conjunction with Felix' `maven-bundle-plugin` or with the `bnd-maven-plugin` (don't have their packaging-type just in my mind), projects with type `eclipse-plugin` are driven by the Manifest.MF and therefore should have that present. Tycho is intended to build existing Eclipse-Plugin (and other PDE) projects with the Manifest-first approach. The other ones mentioned are (more or less) pom-first and are therefore more like Maven projects that also get a manifest generated. So not having a Manifest.MF for those projects would not work.

The question is if that is also applies for the `.project` and `.classpath` file?
But since it worked with the mentioned connectors I assume your answer is yes.
On the other hand even M2E itself probably has the need to generate a `.classpath` file for a bundle (a project with a Manifest):
https://github.com/eclipse-m2e/m2e-core/pull/466
But here we only need that for embedded jars.

But the question would be, how we for example determine where the src-folders are? Do you just use the Maven layout? Because the PDE convention of a folder named `src` would just be an assumption.

I think a minimal reproducer could help here. Can you please provide one?

**Comment by kwin** [comment]
The project configurator should also optionally enable DS annotation support based on the configuration of https://github.com/eclipse-tycho/tycho/tree/master/tycho-ds-plugin.

**Comment by kwin** [comment]
@fbricon recently updated https://github.com/tesla/m2eclipse-tycho so it is not clear whether the idea is to just copy over the relevant code to a new module in this repository.

**Comment by laeubi** [comment]
There is no relevant **Tycho** code in that repository as far as I know, and it does not support DS as far as I can see so there is not much point in copy over things and better start with a fresh implementation of relevant stuff.

**Comment by kwin** [comment]
IMHO https://github.com/tesla/m2eclipse-tycho/blob/main/org.sonatype.tycho.m2e/src/org/sonatype/tycho/m2e/internal/PDEMavenBundlePluginConfigurator.java and the used helper classes are good as a starting point. Adding DS support on top of that would be far easier than starting from scratch.

**Comment by laeubi** [comment]
> Adding DS support on top of that would be far easier than starting from scratch.

Please don't mangle different concerns, **maven-bundle-plugin** is already handled here:

https://github.com/eclipse-m2e/m2e-core/tree/master/org.eclipse.m2e.pde.connector

as everything generic to maven+pde should go there, **tycho-maven-plugin** related (like tycho-ds-plugin-support) should better go to a separate area or at least an own class.
