### ISSUE TITLE
logback RCE CVE-2021-42550

### ISSUE THREAD

**Issue by freedom1b2830** [eclipse-m2e/m2e-core#738]
https://github.com/advisories/GHSA-668q-qrv7-99fm

[scanner](https://github.com/logpresso/CVE-2021-44228-Scanner)
args:[--scan-log4j1 --scan-logback --scan-zip]

[?] Found CVE-2021-42550 (logback 1.2.7) vulnerability in $ECLIPSE_DIR/plugins/ch.qos.logback.classic_1.2.3.v20200428-2012.jar, logback N/A
[?] Found CVE-2021-42550 (logback 1.2.7) vulnerability in $HOME/.p2/pool/plugins/ch.qos.logback.classic_1.1.2.v20171220-1825.jar, logback N/A

https://github.com/eclipse-equinox/equinox.bundles/issues/46

**Comment by HannesWell** [comment]
Thanks for your report.
At the moment the logback dependencies are provided by Eclipse Orbit.
The version either has to be updated there or we could obtain logback-classic/core directly from Maven-Central.
But since orbit also provides a `ch.qos.logback.slf4j` fragment to wire `ch.qos.logback.classic/core` and some dependencies to the slf4j bundle I first have to check how that can be achieved with the bundles from Maven-Central. They already provide an OSGi compliant Manifest.MF but I have to check the details since this is a tricky area.

**Comment by freedom1b2830** [comment]
can you provide a link to issues Eclipse Orbit ?

**Comment by akurtakov** [comment]
https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Orbit

**Comment by freedom1b2830** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=580000

**Comment by HannesWell** [comment]
I have checked how the slf4j-api bundle from Maven-Central is wired to its bindings:
For version<2 it imports a package `org.sfl4j.impl` that the binding has to export.
For version 2 it looks like the OSGi Service Loader Mediator is used.

Any way the original logback from Maven-Central can only be used if also slf4j from Maven-Central is used. And although Eclipse Platform does not use slf4j I suspect that many other Eclipse projects do, so such change should be coordinated across SimRel.

**Comment by akurtakov** [comment]
As it's CVE just update and it should contributed to M1 for September simrel, that should give enough time for others to adjust accordingly.

**Comment by HannesWell** [comment]
I just submitted https://github.com/eclipse-m2e/m2e-core/pull/931, which migrates M2E to logback 1.2.11 (the latest version in the 1.2 stream).
That version or maybe even 1.3 or 1.4 will be then included in the December release of Eclipse.
