### ISSUE TITLE
2.0.0-SNAPSHOT seems wrong

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#935]
We have already release m2e 2.0 (and even 2.0.2), so should the version not be something like 2.1.0-SNAPSHOT (or at laest 2.0.3-SNAPSHOT)?

**Comment by HannesWell** [comment]
> We have already release m2e 2.0 (and even 2.0.2), so should the version not be something like 2.1.0-SNAPSHOT (or at laest 2.0.3-SNAPSHOT)?

We already have m2e 2.0.6: https://download.eclipse.org/technology/m2e/releases/
There have been some fixes before the 2022-09 release

For clearification you are referring to the version of the m2e root pom.xml?
That version has not really been updated in the past, probably since the poms were not relevant (yet) because m2e is not published on Maven-Central. But if we do that and I think we should do that in the future, that version should be aligned.
However we then need to bump the versions of the embedded maven-runtime and archetype even if the jar content has not changed.

**Comment by mickaelistria** [comment]
What is the actual problem?

**Comment by laeubi** [comment]
If you build m2e you get:

> [INFO] Maven Integration for Eclipse (parent) 2.0.0-SNAPSHOT SUCCESS [  2.443 s]

while actually we are developing m2e 2.1.x now ... so I would expect that at least the parent pom is updated to reflect the current (marketing) version of m2e.

**Comment by mickaelistria** [comment]
> so I would expect that at least the parent pom is updated to reflect the current (marketing) version of m2e.

That wouldn't be harmful I guess, but wouldn't be useful either; and I also think that assuming the version of the parent is the version of the distribution is also technically incorrect in general (think of all the Apache projects that have the same parent pom, does it imply they have the same version?). But as long as the pom is not deployed and you're fine spending time on such update, there is not reason to restrain from doing it.

**Comment by laeubi** [comment]
> That wouldn't be harmful I guess, but wouldn't be useful either; and I also think that assuming the version of the parent is the version of the distribution is also technically incorrect in general (think of all the Apache projects that have the same parent pom, does it imply they have the same version?)

That's a bit different, they all use the same (if the always update to the latest version) parent, but each of the projects to have an own version (and of course they don't use snapshots...).

> But as long as the pom is not deployed and you're fine spending time on such update, there is not reason to restrain from doing it.

I think it should be done to better align with maven principles, even though we don not (yet) deploy anything, it might become relevant in the future so I wonder if we could get a general agreement right now.

**Comment by mickaelistria** [comment]
> I think it should be done to better align with maven principles

When we deploy, then the best principle becomes semantic versioning, ie no need to change the version when there have been no change. Maven is not a good citizen on that aspect as it encourages creation of more versions than necessary for all modules.

**Comment by laeubi** [comment]
> > I think it should be done to better align with maven principles
> 
> When we deploy, then the best principle becomes semantic versioning, ie no need to change the version when there have been no change. Maven is not a good citizen on that aspect as it encourages creation of more versions than necessary for all modules.

Actually maven do not *require* this but it is *convenient* to do so... We already have submodule with different versions.

**Comment by HannesWell** [comment]
In general I agree that it would be good to align the parent pom.xml with the 'marketing/branding' version of M2E.

But at least at the moment that would mean that we have to bump the version of the embedded maven-runtime + archetype bundles with each release because their build qualifier changes also with pom.xml changes.
Since we have https://github.com/eclipse-m2e/m2e-core/pull/906 we could actually only bump the version on real content changes and exclude the pom from time-stamp computation but since that pom also drives the changes that are intended to cause a version bump/build-qualifier update I think we have to keep that.

However with https://github.com/eclipse-m2e/m2e-core/pull/466 it is necessary to introduce a M2E-parent pom anyway to not have pom-self-dependencies on the maven-runtime/archetype bundle, so that could be used to decouple things here.



> > > I think it should be done to better align with maven principles
> > 
> > 
> > When we deploy, then the best principle becomes semantic versioning, ie no need to change the version when there have been no change. Maven is not a good citizen on that aspect as it encourages creation of more versions than necessary for all modules.
> 
> Actually maven do not _require_ this but it is _convenient_ to do so... We already have submodule with different versions.

But I wonder what would be done in a case there is a bundle A and bundle B and A depends on B, but only B gets its version increased. Then at least in the Maven world A keeps the dependency only on the old version of B. And a consumer would have to specify the versions of A and B if one wants the latest version of both and cannot rely on transitive dependencies?


> We have already release m2e 2.0 (and even 2.0.2), so should the version not be something like 2.1.0-SNAPSHOT (or at laest 2.0.3-SNAPSHOT)?

Btw. I just bumped the version of the m2e.sdk to 2.1.0 with https://github.com/eclipse-m2e/m2e-core/pull/943.
