### ISSUE TITLE
Use enhanced service tracker to allow to debug issues while getting services provided by DS components

### ISSUE THREAD

**Issue by kwin** [eclipse-m2e/m2e-core#972]
The regular ServiceTracker as e.g. used in https://github.com/eclipse-m2e/m2e-core/blob/0aa663f75337f846f35a610bfb893f9c7c07605f/org.eclipse.m2e.core.ui/src/org/eclipse/m2e/core/ui/internal/M2EUIPluginActivator.java#L176 does not throw a meaningful exception which would allow further debugging.

There should be an enhanced service tracker being used which uses `org.osgi.service.component.runtime.ServiceComponentRuntime` to throw more meaningful messages.

**Comment by laeubi** [comment]
> does not throw a meaningful exception which would allow further debugging.

For what error case?

> There should be an enhanced service tracker being used which uses `org.osgi.service.component.runtime.ServiceComponentRuntime` to throw more meaningful messages.

The general way would be to move all code away from service tracker to declarative components /e4 injection as the have build in debugging / error capabilities...

**Comment by kwin** [comment]
> For what error case?
https://github.com/eclipse-m2e/m2e-core/issues/971

Currently you just see a meaningless NPE.

**Comment by laeubi** [comment]
> Currently you just see a meaningless NPE.

This has nothing to do with servicetracker, that is because the service is not there and then other code fails.

> That is nice, but until that is the case a better tracked is still beneficial. Let me propose something.

I don't think we can add such code... please use the already available felix scr commands to see whats going wrong, the service tracker is not the culprit here but the static access that not uses proper DS/service tracking access...

**Comment by laeubi** [comment]
Please use already exiting tools for this.

**Comment by kwin** [comment]
Wow, closing a PR in seconds it harsh (to say the least).

**Comment by laeubi** [comment]
> Wow, closing a PR/issue in seconds is harsh (to say the least).

As said its not the task of m2e to host OSGi debugging capabilities. There are already tools for this and if you think they are not satisfying better improve there.

Beside that we want to go towards using **more** DI than making using bad static access patterns more comfortable.

**Comment by laeubi** [comment]
Such things are bugs in m2e that needs to be fixed, but not by the user nor do users need to analyze them. Such report should always include a reproducer (from user POV) so we can make sure the issue is fixed, exception messages are not suitable for that as it tells nothing about the cause of the problem if we know that Service X is missing (what is obvious from the NPE in the first place).
